namespace SmartCon.Core.Services;

public static partial class LocalizationService
{
    private static void AddCommonKeys(Dictionary<string, string> ru, Dictionary<string, string> en)
    {
        ru["App_Name"] = "SmartCon";
        en["App_Name"] = "SmartCon";

        ru["Btn_Cancel"] = "Отмена";
        en["Btn_Cancel"] = "Cancel";
        ru["Btn_Connect"] = "Соединить";
        en["Btn_Connect"] = "Connect";
        ru["Btn_Insert"] = "Вставить";
        en["Btn_Insert"] = "Insert";
        ru["Btn_Change"] = "Изменить";
        en["Btn_Change"] = "Change";
        ru["Btn_Save"] = "Сохранить";
        en["Btn_Save"] = "Save";
        ru["Btn_Saved"] = "✓ Сохранено";
        en["Btn_Saved"] = "✓ Saved";
        ru["Btn_Delete"] = "Удалить";
        en["Btn_Delete"] = "Delete";
        ru["Btn_Add"] = "+ Добавить";
        en["Btn_Add"] = "+ Add";
        ru["Btn_Confirm"] = "Подтвердить";
        en["Btn_Confirm"] = "Confirm";
        ru["Btn_Close"] = "Закрыть";
        en["Btn_Close"] = "Close";
        ru["Btn_OK"] = "OK";
        en["Btn_OK"] = "OK";
        ru["Btn_ChangeConnection"] = "Изменить соединение";
        en["Btn_ChangeConnection"] = "Change connection";
        ru["Btn_ConnectAll"] = "Подключить всё";
        en["Btn_ConnectAll"] = "Connect all";
        ru["Btn_AddFamily"] = "▶▶ Добавить";
        en["Btn_AddFamily"] = "▶▶ Add";
        ru["Btn_RemoveFamily"] = "◀◀ Убрать";
        en["Btn_RemoveFamily"] = "◀◀ Remove";
        ru["Btn_Up"] = "▲ Вверх";
        en["Btn_Up"] = "▲ Up";
        ru["Btn_Down"] = "▼ Вниз";
        en["Btn_Down"] = "▼ Down";
        ru["Btn_CheckUpdates"] = "Проверить обновления";
        en["Btn_CheckUpdates"] = "Check for updates";
        ru["Btn_DownloadInstall"] = "Скачать и установить";
        en["Btn_DownloadInstall"] = "Download and install";
        ru["Btn_Import"] = "Импорт…";
        en["Btn_Import"] = "Import…";
        ru["Btn_Export"] = "Экспорт…";
        en["Btn_Export"] = "Export…";
        ru["Btn_Yes"] = "Да";
        en["Btn_Yes"] = "Yes";
        ru["Btn_No"] = "Нет";
        en["Btn_No"] = "No";
        ru["Chk_CheckOnStartup"] = "Проверять при запуске";
        en["Chk_CheckOnStartup"] = "Check on startup";

        ru["Title_EditorSetup"] = "Настройка соединения элементов";
        en["Title_EditorSetup"] = "Connection Setup";
        ru["Heading_EditorSetup"] = "Настройка соединения элементов";
        en["Heading_EditorSetup"] = "Connection Setup";
        ru["Title_Settings"] = "Настройки SmartCon";
        en["Title_Settings"] = "SmartCon Settings";
        ru["Title_FamilySelector"] = "Выбор семейств фитингов";
        en["Title_FamilySelector"] = "Select Fitting Families";
        ru["Title_ConnType"] = "Тип соединения";
        en["Title_ConnType"] = "Connection Type";
        ru["Title_CtcSetup"] = "Назначение типов коннекторов";
        en["Title_CtcSetup"] = "Assign Connector Types";
        ru["Title_About"] = "О SmartCon";
        en["Title_About"] = "About SmartCon";

        ru["Tip_RotateCCW"] = "Повернуть против часовой стрелки";
        en["Tip_RotateCCW"] = "Rotate counter-clockwise";
        ru["Tip_RotationAngle"] = "Угол поворота в градусах";
        en["Tip_RotationAngle"] = "Rotation angle in degrees";
        ru["Tip_RotateCW"] = "Повернуть по часовой стрелке";
        en["Tip_RotateCW"] = "Rotate clockwise";
        ru["Tip_AvailableSizes"] = "Доступные типоразмеры динамического семейства";
        en["Tip_AvailableSizes"] = "Available dynamic family sizes";
        ru["Tip_ChangeSize"] = "Изменить размер динамического семейства";
        en["Tip_ChangeSize"] = "Change dynamic family size";
        ru["Tip_FittingCtc"] = "Отразить типы коннекторов фитинга";
        en["Tip_FittingCtc"] = "Reflect fitting connector types";
        ru["Tip_SelectFitting"] = "Выберите фитинг для соединения";
        en["Tip_SelectFitting"] = "Select fitting for connection";
        ru["Tip_InsertFitting"] = "Вставить выбранный фитинг (примерка)";
        en["Tip_InsertFitting"] = "Insert selected fitting (preview)";
        ru["Tip_ReducerCtc"] = "Отразить типы коннекторов переходника";
        en["Tip_ReducerCtc"] = "Reflect reducer connector types";
        ru["Tip_SelectReducer"] = "Выберите переходник";
        en["Tip_SelectReducer"] = "Select reducer";
        ru["Tip_InsertReducer"] = "Вставить выбранный переходник";
        en["Tip_InsertReducer"] = "Insert selected reducer";
        ru["Tip_ChainDecrement"] = "Отсоединить последний уровень";
        en["Tip_ChainDecrement"] = "Disconnect last level";
        ru["Tip_ChainIncrement"] = "Присоединить следующий уровень";
        en["Tip_ChainIncrement"] = "Connect next level";
        ru["Tip_ConnectAll"] = "Подключить все элементы сети сразу";
        en["Tip_ConnectAll"] = "Connect all network elements at once";
        ru["Tip_SelectFittingFamilies"] = "Нажмите для выбора семейств фитингов (недоступно при «Прямое» — используйте переходы сечения)";
        en["Tip_SelectFittingFamilies"] = "Click to select fitting families (unavailable for Direct — use cross-section transitions)";
        ru["Tip_SelectReducerFamilies"] = "Нажмите для выбора семейств переходников";
        en["Tip_SelectReducerFamilies"] = "Click to select reducer families";
        ru["Tip_ChangeConnection"] = "Переключить на другой свободный коннектор";
        en["Tip_ChangeConnection"] = "Switch to another free connector";
        ru["Tip_Connect"] = "Выполнить соединение элементов";
        en["Tip_Connect"] = "Execute element connection";
        ru["Tip_Import"] = "Загрузить настройки маппинга из JSON-файла (перезапишет текущие)";
        en["Tip_Import"] = "Load mapping settings from a JSON file (overwrites current)";
        ru["Tip_Export"] = "Сохранить настройки маппинга в JSON-файл";
        en["Tip_Export"] = "Save mapping settings to a JSON file";

        ru["Label_Size"] = "Размер:";
        en["Label_Size"] = "Size:";
        ru["Label_Network"] = "Сеть:";
        en["Label_Network"] = "Network:";
        ru["Label_Updates"] = "Обновления";
        en["Label_Updates"] = "Updates";
        ru["Label_AvailableFamilies"] = "Доступные семейства:";
        en["Label_AvailableFamilies"] = "Available families:";
        ru["Label_FamilyFilter"] = "(OST_PipeFitting, MultiPort, 2 коннектора)";
        en["Label_FamilyFilter"] = "(OST_PipeFitting, MultiPort, 2 connectors)";
        ru["Label_SelectedFamilies"] = "Выбранные (порядок = приоритет):";
        en["Label_SelectedFamilies"] = "Selected (order = priority):";
        ru["Label_Family"] = "Семейство: ";
        en["Label_Family"] = "Family: ";
        ru["Label_Symbol"] = "Типоразмер: ";
        en["Label_Symbol"] = "Type: ";
        ru["Label_Connector"] = "Коннектор ";
        en["Label_Connector"] = "Connector ";

        ru["Tab_ConnectorTypes"] = "Типы коннекторов";
        en["Tab_ConnectorTypes"] = "Connector Types";
        ru["Tab_MappingRules"] = "Правила маппинга";
        en["Tab_MappingRules"] = "Mapping Rules";
        ru["Col_Code"] = "Код";
        en["Col_Code"] = "Code";
        ru["Col_Name"] = "Название";
        en["Col_Name"] = "Name";
        ru["Col_Description"] = "Описание";
        en["Col_Description"] = "Description";
        ru["Col_ConnType1"] = "Тип соединения 1";
        en["Col_ConnType1"] = "Connection Type 1";
        ru["Col_ConnType2"] = "Тип соединения 2";
        en["Col_ConnType2"] = "Connection Type 2";
        ru["Col_Direct"] = "Прямое";
        en["Col_Direct"] = "Direct";
        ru["Col_Fittings"] = "Фитинги";
        en["Col_Fittings"] = "Fittings";
        ru["Col_Transitions"] = "Переходы сечения";
        en["Col_Transitions"] = "Cross-Section Transitions";

        ru["Status_Active"] = "Активно";
        en["Status_Active"] = "Active";
        ru["Status_Processing"] = "Обработка…";
        en["Status_Processing"] = "Processing…";
        ru["Status_SessionEnded"] = "Сессия завершена";
        en["Status_SessionEnded"] = "Session ended";
        ru["Msg_AssignCtc"] = "У фитинга не заданы типы коннекторов. Назначьте тип каждому коннектору:";
        en["Msg_AssignCtc"] = "Fitting has no connector types assigned. Assign a type to each connector:";

        ru["About_Author"] = "Автор:";
        en["About_Author"] = "Author:";
        ru["About_Plugin"] = "Плагин:";
        en["About_Plugin"] = "Plugin:";
        ru["About_PluginDesc"] = "MEP коннектор труб для Revit 2025";
        en["About_PluginDesc"] = "MEP Pipe Connector for Revit 2025";
        ru["About_Repo"] = "Репозиторий:";
        en["About_Repo"] = "Repo:";
        ru["About_Language"] = "Язык:";
        en["About_Language"] = "Language:";

        ru["Mapping_NewType"] = "Новый тип";
        en["Mapping_NewType"] = "New type";
        ru["Mapping_NotSelected"] = "(не выбраны)";
        en["Mapping_NotSelected"] = "(not selected)";
        ru["Fitting_DirectConnect"] = "Без фитинга (прямое соединение)";
        en["Fitting_DirectConnect"] = "No fitting (direct connect)";
        ru["Fitting_TypeArrow"] = "Тип {0} → {1}";
        en["Fitting_TypeArrow"] = "Type {0} → {1}";

        ru["Lbl_NoChain"] = "нет цепочки";
        en["Lbl_NoChain"] = "no chain";
        ru["Chain_Levels"] = "уровней";
        en["Chain_Levels"] = "levels";
        ru["FM_Confirm_Title"] = "Подтверждение";
        en["FM_Confirm_Title"] = "Confirm";
        ru["FM_ErrorFormat"] = "Ошибка: {0}";
        en["FM_ErrorFormat"] = "Error: {0}";
    }
}
