namespace SmartCon.Core.Services;

public static partial class LocalizationService
{
    private static void AddProjectManagementKeys(Dictionary<string, string> ru, Dictionary<string, string> en)
    {
        ru["PM_Col_Index"] = "№"; en["PM_Col_Index"] = "#";
        ru["PM_Col_Field"] = "Поле"; en["PM_Col_Field"] = "Field";
        ru["PM_Col_ParseRule"] = "Правило парсинга"; en["PM_Col_ParseRule"] = "Parse Rule";
        ru["PM_Col_Value"] = "Значение"; en["PM_Col_Value"] = "Value";
        ru["PM_Col_Status"] = "✓"; en["PM_Col_Status"] = "✓";
        ru["PM_Col_ValidationCheck"] = "Проверка"; en["PM_Col_ValidationCheck"] = "Check";
        ru["PM_Col_SourceValue"] = "Исходное"; en["PM_Col_SourceValue"] = "Source";
        ru["PM_Col_TargetValue"] = "При экспорте"; en["PM_Col_TargetValue"] = "Export";
        ru["PM_Title_Settings"] = "Настройки экспорта"; en["PM_Title_Settings"] = "Export Settings";
        ru["PM_Title_Progress"] = "Экспорт проекта"; en["PM_Title_Progress"] = "Exporting Project";
        ru["PM_Title_FieldLibrary"] = "Библиотека полей"; en["PM_Title_FieldLibrary"] = "Field Library";
        ru["PM_Title_AllowedValues"] = "Допустимые значения"; en["PM_Title_AllowedValues"] = "Allowed Values";
        ru["PM_Title_ParseRule"] = "Правило парсинга"; en["PM_Title_ParseRule"] = "Parse Rule";
        ru["PM_Result_Success"] = "Проект успешно перемещён в зону Shared."; en["PM_Result_Success"] = "Project exported successfully.";
        ru["PM_Result_Failed"] = "Ошибка экспорта: {0}"; en["PM_Result_Failed"] = "Export failed: {0}";
        ru["PM_Result_NoSettings"] = "Сначала настройьте параметры экспорта через кнопку Settings."; en["PM_Result_NoSettings"] = "Configure export settings first via the Settings button.";
        ru["PM_Result_InvalidName"] = "Имя файла не соответствует шаблону."; en["PM_Result_InvalidName"] = "File name does not match template.";
        ru["PM_Result_SyncFailed"] = "Синхронизация не удалась: {0}"; en["PM_Result_SyncFailed"] = "Synchronization failed: {0}";
        ru["PM_Step_Validate"] = "Проверяем настройки..."; en["PM_Step_Validate"] = "Validating settings...";
        ru["PM_Step_Sync"] = "Синхронизируем ваш проект..."; en["PM_Step_Sync"] = "Synchronizing your project...";
        ru["PM_Step_TempProject"] = "Создаём временный проект..."; en["PM_Step_TempProject"] = "Creating temporary project...";
        ru["PM_Step_Detach"] = "Открываем с отсоединением от ФХ..."; en["PM_Step_Detach"] = "Detaching from central...";
        ru["PM_Step_Purge"] = "Очищаем модель..."; en["PM_Step_Purge"] = "Purging model...";
        ru["PM_Step_Save"] = "Сохраняем в зону Shared..."; en["PM_Step_Save"] = "Saving to Shared folder...";
        ru["PM_Step_Finish"] = "Завершение..."; en["PM_Step_Finish"] = "Finalizing...";
        ru["PM_NamingTemplate"] = "Шаблон имени файла"; en["PM_NamingTemplate"] = "File Name Template";
        ru["PM_Blocks"] = "Блоки"; en["PM_Blocks"] = "Blocks";
        ru["PM_AddBlock"] = "+ Блок"; en["PM_AddBlock"] = "+ Block";
        ru["PM_RemoveBlock"] = "- Блок"; en["PM_RemoveBlock"] = "- Block";
        ru["PM_MoveUp"] = "Переместить вверх"; en["PM_MoveUp"] = "Move up";
        ru["PM_MoveDown"] = "Переместить вниз"; en["PM_MoveDown"] = "Move down";
        ru["PM_FieldLibrary"] = "Библиотека полей..."; en["PM_FieldLibrary"] = "Field Library...";
        ru["PM_ExportMappings"] = "Маппинг экспорта"; en["PM_ExportMappings"] = "Export Mapping";
        ru["PM_AddMapping"] = "+ Маппинг"; en["PM_AddMapping"] = "+ Mapping";
        ru["PM_RemoveMapping"] = "- Маппинг"; en["PM_RemoveMapping"] = "- Mapping";
        ru["PM_Preview"] = "Предпросмотр"; en["PM_Preview"] = "Preview";
        ru["PM_CurrentName"] = "Текущее:"; en["PM_CurrentName"] = "Current:";
        ru["PM_SharedName"] = "Shared:"; en["PM_SharedName"] = "Shared:";
        ru["PM_Col_FieldName"] = "Имя поля"; en["PM_Col_FieldName"] = "Field Name";
        ru["PM_Col_DisplayName"] = "Отображение"; en["PM_Col_DisplayName"] = "Display Name";
        ru["PM_Col_Description"] = "Описание"; en["PM_Col_Description"] = "Description";
        ru["PM_Col_Validation"] = "Валидация"; en["PM_Col_Validation"] = "Validation";
        ru["PM_Col_Min"] = "Мин"; en["PM_Col_Min"] = "Min";
        ru["PM_Col_Max"] = "Макс"; en["PM_Col_Max"] = "Max";
        ru["PM_AllowedValuesButton"] = "Допустимые значения..."; en["PM_AllowedValuesButton"] = "Allowed Values...";
        ru["PM_DuplicateField"] = "Дублировать"; en["PM_DuplicateField"] = "Duplicate";
        ru["PM_ValidationMode"] = "Режим валидации:"; en["PM_ValidationMode"] = "Validation mode:";
        ru["PM_MinLength"] = "Мин. длина:"; en["PM_MinLength"] = "Min length:";
        ru["PM_MaxLength"] = "Макс. длина:"; en["PM_MaxLength"] = "Max length:";
        ru["PM_AddValue"] = "+ Добавить"; en["PM_AddValue"] = "+ Add";
        ru["PM_RemoveValue"] = "- Удалить"; en["PM_RemoveValue"] = "- Remove";
        ru["PM_ParseMode"] = "Режим:"; en["PM_ParseMode"] = "Mode:";
        ru["PM_Delimiter"] = "Разделитель:"; en["PM_Delimiter"] = "Delimiter:";
        ru["PM_SegmentIndex"] = "Сегмент:"; en["PM_SegmentIndex"] = "Segment:";
        ru["PM_SegmentCount"] = "Кол-во:"; en["PM_SegmentCount"] = "Count:";
        ru["PM_CharCount"] = "Кол-во симв.:"; en["PM_CharCount"] = "Char count:";
        ru["PM_OpenMarker"] = "Откр.:"; en["PM_OpenMarker"] = "Open:";
        ru["PM_CloseMarker"] = "Закр.:"; en["PM_CloseMarker"] = "Close:";
        ru["PM_Marker"] = "Маркер:"; en["PM_Marker"] = "Marker:";
        ru["PM_CharOffset"] = "Пропуск:"; en["PM_CharOffset"] = "Skip:";
        ru["PM_MarkerIndex"] = "№ символа:"; en["PM_MarkerIndex"] = "Symbol #:";
        ru["PM_FileName"] = "Файл:"; en["PM_FileName"] = "File:";
        ru["PM_Result"] = "Результат:"; en["PM_Result"] = "Result:";
        ru["PM_Remaining"] = "Остаток:"; en["PM_Remaining"] = "Remaining:";
        ru["PM_ValidField"] = "✓"; en["PM_ValidField"] = "✓";
        ru["PM_InvalidField"] = "✗"; en["PM_InvalidField"] = "✗";

        ru["PM_ValMode_None"] = "Любое значение"; en["PM_ValMode_None"] = "Any value";
        ru["PM_ValMode_None_Desc"] = "Без ограничений: поле принимает любое значение"; en["PM_ValMode_None_Desc"] = "No restrictions: field accepts any value";
        ru["PM_ValMode_List"] = "Только из списка"; en["PM_ValMode_List"] = "From list only";
        ru["PM_ValMode_List_Desc"] = "Значение должно совпадать с одним из допустимых значений"; en["PM_ValMode_List_Desc"] = "Value must match one of the allowed values";
        ru["PM_ValMode_Length"] = "По длине"; en["PM_ValMode_Length"] = "By length";
        ru["PM_ValMode_Length_Desc"] = "Ограничение только на минимальную и максимальную длину текста"; en["PM_ValMode_Length_Desc"] = "Only minimum and maximum text length constraints";

        ru["PM_ParseMode_Delimiter"] = "По разделителю"; en["PM_ParseMode_Delimiter"] = "By delimiter";
        ru["PM_ParseMode_Delimiter_Desc"] = "Разбивает текст по разделителю и берёт указанный сегмент (нумерация с 0)"; en["PM_ParseMode_Delimiter_Desc"] = "Splits text by delimiter and takes the specified segment (0-based)";
        ru["PM_ParseMode_FixedWidth"] = "Фиксированная ширина"; en["PM_ParseMode_FixedWidth"] = "Fixed width";
        ru["PM_ParseMode_FixedWidth_Desc"] = "Берёт заданное количество символов от начала"; en["PM_ParseMode_FixedWidth_Desc"] = "Takes a fixed number of characters from the start";
        ru["PM_ParseMode_Between"] = "Между маркерами"; en["PM_ParseMode_Between"] = "Between markers";
        ru["PM_ParseMode_Between_Desc"] = "Извлекает текст между открывающим и закрывающим маркерами"; en["PM_ParseMode_Between_Desc"] = "Extracts text between opening and closing markers";
        ru["PM_ParseMode_After"] = "После маркера"; en["PM_ParseMode_After"] = "After marker";
        ru["PM_ParseMode_After_Desc"] = "Берёт весь текст после указанного маркера"; en["PM_ParseMode_After_Desc"] = "Takes all text after the specified marker";
        ru["PM_ParseMode_Remainder"] = "Остаток"; en["PM_ParseMode_Remainder"] = "Remainder";
        ru["PM_ParseMode_Remainder_Desc"] = "Берёт весь оставшийся текст после предыдущих блоков"; en["PM_ParseMode_Remainder_Desc"] = "Takes all remaining text after previous blocks";

        ru["PM_Tab_General"] = "Общие"; en["PM_Tab_General"] = "General";
        ru["PM_Tab_Purge"] = "Очистка"; en["PM_Tab_Purge"] = "Purge";
        ru["PM_Tab_Views"] = "Виды"; en["PM_Tab_Views"] = "Views";
        ru["PM_Tab_Naming"] = "Именование"; en["PM_Tab_Naming"] = "Naming";
        ru["PM_CurrentFile"] = "Текущий файл"; en["PM_CurrentFile"] = "Current File";
        ru["PM_FilePath"] = "Путь:"; en["PM_FilePath"] = "Path:";
        ru["PM_Folder"] = "Папка:"; en["PM_Folder"] = "Folder:";
        ru["PM_SharedFolder"] = "Папка Shared"; en["PM_SharedFolder"] = "Shared Folder";
        ru["PM_Browse"] = "Обзор..."; en["PM_Browse"] = "Browse...";
        ru["PM_SyncBefore"] = "Синхронизировать перед экспортом"; en["PM_SyncBefore"] = "Synchronize before export";
        ru["PM_PurgeTitle"] = "Выберите элементы для удаления из Shared-файла:"; en["PM_PurgeTitle"] = "Select elements to remove from the Shared file:";
        ru["PM_PurgeRvtLinks"] = "RVT-связи"; en["PM_PurgeRvtLinks"] = "RVT Links";
        ru["PM_PurgeCadImports"] = "CAD / IFC-связи"; en["PM_PurgeCadImports"] = "CAD / IFC Links";
        ru["PM_PurgeImages"] = "Растровые изображения"; en["PM_PurgeImages"] = "Raster Images";
        ru["PM_PurgePointClouds"] = "Облака точек"; en["PM_PurgePointClouds"] = "Point Clouds";
        ru["PM_PurgeGroups"] = "Группы (разгруппировать)"; en["PM_PurgeGroups"] = "Groups (ungroup)";
        ru["PM_PurgeAssemblies"] = "Сборки (разобрать)"; en["PM_PurgeAssemblies"] = "Assemblies (disassemble)";
        ru["PM_PurgeSpaces"] = "MEP-пространства"; en["PM_PurgeSpaces"] = "MEP Spaces";
        ru["PM_PurgeRebar"] = "Арматура (Rebar)"; en["PM_PurgeRebar"] = "Rebar";
        ru["PM_PurgeFabric"] = "Арматурные каркасы"; en["PM_PurgeFabric"] = "Fabric Reinforcement";
        ru["PM_PurgeSheets"] = "Листы и чертежи"; en["PM_PurgeSheets"] = "Sheets and Drawings";
        ru["PM_PurgeSchedules"] = "Спецификации"; en["PM_PurgeSchedules"] = "Schedules";
        ru["PM_PurgeUnused"] = "Неиспользуемые элементы (Purge)"; en["PM_PurgeUnused"] = "Unused Elements (Purge)";
        ru["PM_SelectAll"] = "Все"; en["PM_SelectAll"] = "All";
        ru["PM_DeselectAll"] = "Ни одного"; en["PM_DeselectAll"] = "None";
        ru["PM_ViewsTitle"] = "Виды для сохранения в Shared-файле:"; en["PM_ViewsTitle"] = "Views to keep in the Shared file:";
        ru["PM_RefreshViews"] = "Обновить список"; en["PM_RefreshViews"] = "Refresh List";
        ru["PM_SearchViews"] = "Поиск вида..."; en["PM_SearchViews"] = "Search views...";
        ru["PM_SelectedCount"] = "Выбрано:"; en["PM_SelectedCount"] = "Selected:";
        ru["PM_AddField"] = "+ Добавить"; en["PM_AddField"] = "+ Add";
        ru["PM_RemoveField"] = "- Удалить"; en["PM_RemoveField"] = "- Remove";
        ru["PM_ExportName_CurrentLabel"] = "Текущее имя: "; en["PM_ExportName_CurrentLabel"] = "Current name: ";
        ru["PM_ExportName_FillFields"] = "Заполните поля для имени экспорта:"; en["PM_ExportName_FillFields"] = "Fill fields for export name:";
        ru["PM_ExportName_Preview"] = "Предпросмотр: "; en["PM_ExportName_Preview"] = "Preview: ";
    }
}
