namespace SmartCon.Core.Services;

public static partial class LocalizationService
{
    private static void AddFamilyManagerKeys(Dictionary<string, string> ru, Dictionary<string, string> en)
    {
        ru["FM_SearchPlaceholder"] = "Поиск семейств..."; en["FM_SearchPlaceholder"] = "Search families...";
        ru["FM_Import"] = "Импорт"; en["FM_Import"] = "Import";
        ru["FM_ImportFile"] = "Импорт файла"; en["FM_ImportFile"] = "Import File";
        ru["FM_ImportFolder"] = "Импорт папки"; en["FM_ImportFolder"] = "Import Folder";
        ru["FM_LoadToProject"] = "Загрузить в проект"; en["FM_LoadToProject"] = "Load to Project";
        ru["FM_LoadAndPlace"] = "Загрузить и разместить"; en["FM_LoadAndPlace"] = "Load and Place";
        ru["FM_ExtractTypes"] = "Извлечь типоразмеры"; en["FM_ExtractTypes"] = "Extract Types";
        ru["FM_ImportData"] = "Импорт данных"; en["FM_ImportData"] = "Import Data";
        ru["FM_PlaceType"] = "Разместить тип"; en["FM_PlaceType"] = "Place Type";
        ru["FM_EditMetadata"] = "Редактировать"; en["FM_EditMetadata"] = "Edit";
        ru["FM_NoActiveDocument"] = "Нет активного документа"; en["FM_NoActiveDocument"] = "No active document";
        ru["FM_ImportProgress"] = "Импорт {0} из {1}..."; en["FM_ImportProgress"] = "Importing {0} of {1}...";
        ru["FM_ColName"] = "Имя"; en["FM_ColName"] = "Name";
        ru["FM_ColStatus"] = "Статус"; en["FM_ColStatus"] = "Status";
        ru["FM_ColVersion"] = "Версия"; en["FM_ColVersion"] = "Version";
        ru["FM_ColUpdated"] = "Обновлено"; en["FM_ColUpdated"] = "Updated";
        ru["FM_Save"] = "Сохранить"; en["FM_Save"] = "Save";
        ru["FM_Cancel"] = "Отмена"; en["FM_Cancel"] = "Cancel";
        ru["FM_Name"] = "Имя"; en["FM_Name"] = "Name";
        ru["FM_Description"] = "Описание"; en["FM_Description"] = "Description";
        ru["FM_Category"] = "Категория"; en["FM_Category"] = "Category";
        ru["FM_Tags"] = "Теги (через запятую)"; en["FM_Tags"] = "Tags (comma-separated)";
        ru["FM_Status"] = "Статус"; en["FM_Status"] = "Status";
        ru["FM_ImportSuccess"] = "Импортировано: {0}"; en["FM_ImportSuccess"] = "Imported: {0}";
        ru["FM_ImportError"] = "Ошибка импорта: {0}"; en["FM_ImportError"] = "Import error: {0}";
        ru["FM_ImportPrepareError"] = "Ошибка подготовки"; en["FM_ImportPrepareError"] = "Preparation error";
        ru["FM_FamilyFileNotFound"] = "Файл семейства не найден"; en["FM_FamilyFileNotFound"] = "Family file not found";
        ru["FM_ImportResultFormat"] = "Импортировано: {0} типоразмеров, {1} значений найдено"; en["FM_ImportResultFormat"] = "Imported: {0} types, {1} values found";
        ru["FM_ImportDataError"] = "Ошибка импорта: {0}"; en["FM_ImportDataError"] = "Import error: {0}";
        ru["FM_ImportFileToCategory"] = "Импорт файла"; en["FM_ImportFileToCategory"] = "Import file";
        ru["FM_ImportFolderToCategory"] = "Импорт папки"; en["FM_ImportFolderToCategory"] = "Import folder";
        ru["FM_ImportDataForCategory"] = "Импорт данных"; en["FM_ImportDataForCategory"] = "Import data";
        ru["FM_ImportDataProgress"] = "Обработка {0} из {1}: {2}"; en["FM_ImportDataProgress"] = "Processing {0} of {1}: {2}";
        ru["FM_NoFamiliesInCategory"] = "В категории нет семейств"; en["FM_NoFamiliesInCategory"] = "No families in category";
        ru["FM_LoadSuccess"] = "Семейство \"{0}\" загружено в проект"; en["FM_LoadSuccess"] = "Family \"{0}\" loaded into project";
        ru["FM_LoadAndPlaceSuccess"] = "Семейство \"{0}\" — нажмите для размещения"; en["FM_LoadAndPlaceSuccess"] = "Family \"{0}\" — click to place";
        ru["FM_LoadError"] = "Ошибка загрузки: {0}"; en["FM_LoadError"] = "Load error: {0}";
        ru["FM_DuplicateSkipped"] = "Дубликат пропущен: {0}"; en["FM_DuplicateSkipped"] = "Duplicate skipped: {0}";
        ru["FM_Title_MetadataEdit"] = "Редактирование метаданных"; en["FM_Title_MetadataEdit"] = "Edit Metadata";

        ru["FM_DbSwitched"] = "База данных переключена на: {0}"; en["FM_DbSwitched"] = "Database switched to: {0}";
        ru["FM_DbSwitchError"] = "Ошибка переключения базы данных"; en["FM_DbSwitchError"] = "Error switching database";
        ru["FM_DbCreated"] = "База данных \"{0}\" создана"; en["FM_DbCreated"] = "Database \"{0}\" created";
        ru["FM_DbCreateError"] = "Ошибка создания БД: {0}"; en["FM_DbCreateError"] = "Error creating database: {0}";
        ru["FM_DbDeleted"] = "База данных \"{0}\" удалена"; en["FM_DbDeleted"] = "Database \"{0}\" deleted";
        ru["FM_DbDeleteError"] = "Ошибка удаления БД: {0}"; en["FM_DbDeleteError"] = "Error deleting database: {0}";
        ru["FM_DbDeleteSingle"] = "Нельзя удалить единственную базу данных."; en["FM_DbDeleteSingle"] = "Cannot delete the only database.";
        ru["FM_DbDeleteTitle"] = "Удаление базы данных"; en["FM_DbDeleteTitle"] = "Delete Database";
        ru["FM_DbDeletePrompt"] = "Введите \"{0}\" для подтверждения удаления:"; en["FM_DbDeletePrompt"] = "Enter \"{0}\" to confirm deletion:";
        ru["FM_DbNewTitle"] = "Новая база данных"; en["FM_DbNewTitle"] = "New Database";
        ru["FM_DbNewPrompt"] = "Введите название новой базы данных:"; en["FM_DbNewPrompt"] = "Enter new database name:";
        ru["FM_DbNewDefault"] = "Новый каталог"; en["FM_DbNewDefault"] = "New Catalog";
        ru["FM_FamilyDeleted"] = "Семейство \"{0}\" удалено из каталога"; en["FM_FamilyDeleted"] = "Family \"{0}\" deleted from catalog";
        ru["FM_FamilyDeleteError"] = "Ошибка удаления семейства"; en["FM_FamilyDeleteError"] = "Error deleting family";
        ru["FM_FamilyDeleteTitle"] = "Удаление семейства"; en["FM_FamilyDeleteTitle"] = "Delete Family";
        ru["FM_FamilyDeletePrompt"] = "Удалить семейство \"{0}\" из каталога?"; en["FM_FamilyDeletePrompt"] = "Delete family \"{0}\" from catalog?";
        ru["FM_DeleteFromCatalog"] = "Удалить из каталога"; en["FM_DeleteFromCatalog"] = "Delete from catalog";
        ru["FM_NoVersionSelected"] = "Версия не выбрана"; en["FM_NoVersionSelected"] = "No version selected";
        ru["FM_NoCategory"] = "Без категории"; en["FM_NoCategory"] = "No category";
        ru["FM_DbSelectPath"] = "Выберите расположение базы данных"; en["FM_DbSelectPath"] = "Select database location";
        ru["FM_Disconnect"] = "Отключить базу данных"; en["FM_Disconnect"] = "Disconnect database";

        ru["FM_Update"] = "Обновить"; en["FM_Update"] = "Update";
        ru["FM_UpdateSuccess"] = "Обновлено: {0} → {1}"; en["FM_UpdateSuccess"] = "Updated: {0} → {1}";
        ru["FM_UpdateIdentical"] = "Файл идентичен текущей версии: {0}"; en["FM_UpdateIdentical"] = "File is identical to current version: {0}";
        ru["FM_UpdateError"] = "Ошибка обновления: {0}"; en["FM_UpdateError"] = "Update error: {0}";

        ru["FM_CTE_Title"] = "Редактор дерева категорий"; en["FM_CTE_Title"] = "Category Tree Editor";
        ru["FM_CTE_AddRoot"] = "+ Корень"; en["FM_CTE_AddRoot"] = "+ Root";
        ru["FM_CTE_AddChild"] = "+ Вложенная"; en["FM_CTE_AddChild"] = "+ Child";
        ru["FM_CTE_Rename"] = "Переименовать"; en["FM_CTE_Rename"] = "Rename";
        ru["FM_CTE_Delete"] = "Удалить"; en["FM_CTE_Delete"] = "Delete";
        ru["FM_CTE_Import"] = "Импорт"; en["FM_CTE_Import"] = "Import";
        ru["FM_CTE_Export"] = "Экспорт"; en["FM_CTE_Export"] = "Export";
        ru["FM_CTE_Close"] = "Закрыть"; en["FM_CTE_Close"] = "Close";
        ru["FM_CTE_AddCategory"] = "Добавить категорию"; en["FM_CTE_AddCategory"] = "Add Category";
        ru["FM_CTE_CategoryName"] = "Название категории:"; en["FM_CTE_CategoryName"] = "Category name:";
        ru["FM_CTE_AddSubcategory"] = "Добавить подкатегорию"; en["FM_CTE_AddSubcategory"] = "Add Subcategory";
        ru["FM_CTE_SubcategoryName"] = "Название подкатегории:"; en["FM_CTE_SubcategoryName"] = "Subcategory name:";
        ru["FM_CTE_NewName"] = "Новое название:"; en["FM_CTE_NewName"] = "New name:";
        ru["FM_CTE_DeleteCategory"] = "Удаление категории"; en["FM_CTE_DeleteCategory"] = "Delete Category";
        ru["FM_CTE_DeleteConfirm"] = "Удалить \"{0}\"? {1} семейств будут перемещены в \"{2}\"."; en["FM_CTE_DeleteConfirm"] = "Delete \"{0}\"? {1} families will be moved to \"{2}\".";
        ru["FM_CTE_DeleteEmpty"] = "Удалить \"{0}\"?"; en["FM_CTE_DeleteEmpty"] = "Delete \"{0}\"?";
        ru["FM_CTE_Deleted"] = "Удалено: {0}"; en["FM_CTE_Deleted"] = "Deleted: {0}";
        ru["FM_CTE_Saved"] = "Сохранено"; en["FM_CTE_Saved"] = "Saved";
        ru["FM_CTE_ImportTree"] = "Импорт дерева категорий"; en["FM_CTE_ImportTree"] = "Import Category Tree";
        ru["FM_CTE_Imported"] = "Импортировано {0} категорий"; en["FM_CTE_Imported"] = "Imported {0} categories";
        ru["FM_CTE_ExportTree"] = "Экспорт дерева категорий"; en["FM_CTE_ExportTree"] = "Export Category Tree";
        ru["FM_CTE_Exported"] = "Экспортировано в {0}"; en["FM_CTE_Exported"] = "Exported to {0}";
        ru["FM_CTE_AttrExists"] = "Атрибут \"{0}\" уже существует."; en["FM_CTE_AttrExists"] = "Attribute \"{0}\" already exists.";
        ru["FM_CTE_ExportAttrs"] = "Экспорт атрибутов"; en["FM_CTE_ExportAttrs"] = "Export Attributes";
        ru["FM_CTE_ExportFull"] = "Экспорт полного пакета"; en["FM_CTE_ExportFull"] = "Export Full Package";
        ru["FM_CTE_CategoriesAndAttrs"] = "Категории и атрибуты"; en["FM_CTE_CategoriesAndAttrs"] = "Categories & Attributes";
        ru["FM_CTE_CategoryTree"] = "Дерево категорий"; en["FM_CTE_CategoryTree"] = "Category Tree";
        ru["FM_CTE_AttributesFor"] = "Атрибуты:"; en["FM_CTE_AttributesFor"] = "Attributes:";
        ru["FM_CTE_SelectCategory"] = "Выберите категорию"; en["FM_CTE_SelectCategory"] = "Select a category";
        ru["FM_CTE_SelectCategoryHint"] = "Выберите категорию для управления атрибутами"; en["FM_CTE_SelectCategoryHint"] = "Select a category to manage attributes";
        ru["FM_CTE_AllGroups"] = "Все атрибуты"; en["FM_CTE_AllGroups"] = "All attributes";
        ru["FM_CTE_SearchAttrs"] = "Поиск атрибутов..."; en["FM_CTE_SearchAttrs"] = "Search attributes...";
        ru["FM_CTE_Inherited"] = "(наследован)"; en["FM_CTE_Inherited"] = "(inherited)";
        ru["FM_CTE_NewAttrName"] = "Новый атрибут"; en["FM_CTE_NewAttrName"] = "New attribute";
        ru["FM_CTE_AddAttr"] = "Добавить"; en["FM_CTE_AddAttr"] = "Add";
        ru["FM_CTE_AttrLibrary"] = "Библиотека атрибутов..."; en["FM_CTE_AttrLibrary"] = "Attribute Library...";
        ru["FM_CTE_ImportJson"] = "Импорт из JSON"; en["FM_CTE_ImportJson"] = "Import JSON";
        ru["FM_CTE_UnsavedChangesTitle"] = "Несохранённые изменения"; en["FM_CTE_UnsavedChangesTitle"] = "Unsaved Changes";
        ru["FM_CTE_UnsavedChangesMessage"] = "У вас есть несохранённые изменения. Сохранить перед закрытием?"; en["FM_CTE_UnsavedChangesMessage"] = "You have unsaved changes. Save before closing?";
        ru["FM_CTE_ExportColon"] = "Экспорт:"; en["FM_CTE_ExportColon"] = "Export:";
        ru["FM_CTE_ContextMenu_Rename"] = "Переименовать"; en["FM_CTE_ContextMenu_Rename"] = "Rename";
        ru["FM_CTE_ContextMenu_AddChild"] = "Добавить подкатегорию"; en["FM_CTE_ContextMenu_AddChild"] = "Add Subcategory";
        ru["FM_CTE_ContextMenu_Delete"] = "Удалить"; en["FM_CTE_ContextMenu_Delete"] = "Delete";
        ru["FM_CTE_NewCategory"] = "Новая категория"; en["FM_CTE_NewCategory"] = "New Category";
        ru["FM_CTE_Attributes"] = "Атрибуты"; en["FM_CTE_Attributes"] = "Attributes";

        ru["FM_CP_Title"] = "Выбор категории"; en["FM_CP_Title"] = "Select Category";
        ru["FM_CP_Clear"] = "Сбросить"; en["FM_CP_Clear"] = "Clear";

        ru["FM_Tip_CreateDb"] = "Создать новую базу данных"; en["FM_Tip_CreateDb"] = "Create new database";
        ru["FM_Tip_ConnectDb"] = "Подключить существующую базу данных"; en["FM_Tip_ConnectDb"] = "Connect existing database";
        ru["FM_Tip_EditCategories"] = "Редактировать категории"; en["FM_Tip_EditCategories"] = "Edit categories";

        ru["FM_Properties"] = "Свойства"; en["FM_Properties"] = "Properties";
        ru["FM_Props_SelectImage"] = "Выберите изображение"; en["FM_Props_SelectImage"] = "Select image";
        ru["FM_Props_AddFile"] = "Выберите файл"; en["FM_Props_AddFile"] = "Select file";
        ru["FM_Tab_General"] = "Общие"; en["FM_Tab_General"] = "General";
        ru["FM_Tab_Content"] = "Контент"; en["FM_Tab_Content"] = "Content";
        ru["FM_Tab_Attributes"] = "Атрибуты"; en["FM_Tab_Attributes"] = "Attributes";
        ru["FM_Tab_3DView"] = "3D Просмотр"; en["FM_Tab_3DView"] = "3D Preview";
        ru["FM_Props_Manufacturer"] = "Производитель"; en["FM_Props_Manufacturer"] = "Manufacturer";
        ru["FM_Props_Version"] = "Версия"; en["FM_Props_Version"] = "Version";
        ru["FM_Props_Size"] = "Размер"; en["FM_Props_Size"] = "Size";
        ru["FM_Props_Created"] = "Создано"; en["FM_Props_Created"] = "Created";
        ru["FM_Props_Updated"] = "Обновлено"; en["FM_Props_Updated"] = "Updated";
        ru["FM_Props_NoAvatar"] = "Нет изображения"; en["FM_Props_NoAvatar"] = "No image";
        ru["FM_Props_ChangeImage"] = "Сменить"; en["FM_Props_ChangeImage"] = "Change";
        ru["FM_Props_RemoveImage"] = "Удалить"; en["FM_Props_RemoveImage"] = "Remove";
        ru["FM_Props_Images"] = "Изображения"; en["FM_Props_Images"] = "Images";
        ru["FM_Props_Videos"] = "Видео"; en["FM_Props_Videos"] = "Videos";
        ru["FM_Props_Documents"] = "Документы"; en["FM_Props_Documents"] = "Documents";
        ru["FM_Props_LookupTables"] = "Таблицы поиска (CSV)"; en["FM_Props_LookupTables"] = "Lookup Tables (CSV)";
        ru["FM_Props_Spreadsheets"] = "Электронные таблицы (XLS)"; en["FM_Props_Spreadsheets"] = "Spreadsheets (XLS)";
        ru["FM_Props_Models3D"] = "3D Модели"; en["FM_Props_Models3D"] = "3D Models";
        ru["FM_Props_Other"] = "Прочие файлы"; en["FM_Props_Other"] = "Other Files";
        ru["FM_Props_Open"] = "Открыть"; en["FM_Props_Open"] = "Open";
        ru["FM_Props_Delete"] = "Удалить"; en["FM_Props_Delete"] = "Delete";
        ru["FM_Props_SetPrimary"] = "Сделать главной"; en["FM_Props_SetPrimary"] = "Set as primary";
        ru["FM_Props_Add"] = "+ Добавить"; en["FM_Props_Add"] = "+ Add";
        ru["FM_Props_NoAttributes"] = "Атрибуты не извлечены"; en["FM_Props_NoAttributes"] = "No attributes extracted";
        ru["FM_Props_NoAttributesDesc"] = "Для извлечения атрибутов семейство будет временно загружено в Revit"; en["FM_Props_NoAttributesDesc"] = "To extract attributes, the family will be temporarily loaded into Revit";
        ru["FM_Props_PresetCategory"] = "Категория: {0}"; en["FM_Props_PresetCategory"] = "Category: {0}";
        ru["FM_Props_NoPresets"] = "Нет пресетов для этой категории"; en["FM_Props_NoPresets"] = "No presets for this category";
        ru["FM_Props_3DComingSoon"] = "3D-просмотр модели (GLB) — в разработке"; en["FM_Props_3DComingSoon"] = "3D model preview (GLB) — coming soon";
        ru["FM_Props_3DDesc"] = "Здесь будет интерактивный 3D-просмотр модели семейства. Вы сможете вращать, масштабировать и изучать геометрию перед загрузкой в проект."; en["FM_Props_3DDesc"] = "Interactive 3D preview of the family model will be available here. You will be able to rotate, zoom, and explore geometry before loading into the project.";
        ru["FM_Props_FileInfo"] = "Информация о файле"; en["FM_Props_FileInfo"] = "File Information";
        ru["FM_Props_Title"] = "Свойства семейства"; en["FM_Props_Title"] = "Family Properties";
        ru["FM_Props_NoAssets"] = "Нет файлов"; en["FM_Props_NoAssets"] = "No files";
        ru["FM_Props_ConfigurePreset"] = "Настроить пресет..."; en["FM_Props_ConfigurePreset"] = "Configure preset...";
        ru["FM_Props_ExtractAttributes"] = "Извлечь атрибуты"; en["FM_Props_ExtractAttributes"] = "Extract attributes";
        ru["FM_Props_NoCategoryAttr"] = "Семейству не назначена категория. Назначьте категорию, чтобы определить обязательные атрибуты."; en["FM_Props_NoCategoryAttr"] = "No category assigned. Assign a category to define required attributes.";
        ru["FM_Props_NoBindingsAttr"] = "Для категории нет обязательных атрибутов."; en["FM_Props_NoBindingsAttr"] = "No required attributes for this category.";
        ru["FM_Props_NotImported"] = "Атрибуты ещё не импортированы"; en["FM_Props_NotImported"] = "Attributes not yet imported";
        ru["FM_Props_NotImportedDesc"] = "Используйте команду «Импорт данных» из контекстного меню семейства в основной панели."; en["FM_Props_NotImportedDesc"] = "Use the 'Import Data' command from the family's context menu in the main panel.";
        ru["FM_Props_Completeness"] = "Полнота"; en["FM_Props_Completeness"] = "Completeness";
        ru["FM_Props_TypeSize"] = "Типоразмер"; en["FM_Props_TypeSize"] = "Type";
        ru["FM_Props_XlsNote"] = "XLS — рабочий файл, CSV — для Revit Lookup Table"; en["FM_Props_XlsNote"] = "XLS — working file, CSV — for Revit Lookup Table";

        ru["FM_PE_Title"] = "Редактор пресета атрибутов"; en["FM_PE_Title"] = "Attribute Preset Editor";
        ru["FM_PE_ParameterName"] = "Имя параметра"; en["FM_PE_ParameterName"] = "Parameter Name";
        ru["FM_PE_DisplayName"] = "Отображаемое имя"; en["FM_PE_DisplayName"] = "Display Name";
        ru["FM_PE_AddParameter"] = "+ Добавить параметр"; en["FM_PE_AddParameter"] = "+ Add parameter";
        ru["FM_PE_RemoveParameter"] = "- Удалить"; en["FM_PE_RemoveParameter"] = "- Remove";

        ru["FM_FamilyNotFoundAfterLoad"] = "Семейство не найдено после загрузки"; en["FM_FamilyNotFoundAfterLoad"] = "Family not found after loading";
        ru["FM_CannotDisconnectOnlyDatabase"] = "Нельзя отключить единственную базу данных."; en["FM_CannotDisconnectOnlyDatabase"] = "Cannot disconnect the only database.";

        ru["FM_AL_Title"] = "Библиотека атрибутов"; en["FM_AL_Title"] = "Attribute Library";
        ru["FM_AL_Search"] = "Поиск атрибутов..."; en["FM_AL_Search"] = "Search attributes...";
        ru["FM_AL_Name"] = "Имя"; en["FM_AL_Name"] = "Name";
        ru["FM_AL_Group"] = "Группа"; en["FM_AL_Group"] = "Group";
        ru["FM_AL_Active"] = "Активен"; en["FM_AL_Active"] = "Active";
        ru["FM_AL_UsedIn"] = "Используется в"; en["FM_AL_UsedIn"] = "Used in";
        ru["FM_AL_Delete"] = "Удалить"; en["FM_AL_Delete"] = "Delete";
        ru["FM_AL_Close"] = "Закрыть"; en["FM_AL_Close"] = "Close";
        ru["FM_AL_ConfirmDelete"] = "Удалить атрибут \"{0}\"? Он используется в {1} категориях."; en["FM_AL_ConfirmDelete"] = "Delete attribute \"{0}\"? It is used in {1} categories.";
        ru["FM_AL_ConfirmDeleteEmpty"] = "Удалить атрибут \"{0}\"?"; en["FM_AL_ConfirmDeleteEmpty"] = "Delete attribute \"{0}\"?";
        ru["FM_AL_Add"] = "Добавить"; en["FM_AL_Add"] = "Add";
        ru["FM_AL_Rename"] = "Переименовать"; en["FM_AL_Rename"] = "Rename";
        ru["FM_AL_SetGroup"] = "Группа"; en["FM_AL_SetGroup"] = "Group";
        ru["FM_AL_EnterName"] = "Имя атрибута:"; en["FM_AL_EnterName"] = "Attribute name:";
        ru["FM_AL_EnterGroup"] = "Имя группы:"; en["FM_AL_EnterGroup"] = "Group name:";
        ru["FM_AL_DeactivateTitle"] = "Деактивация атрибута"; en["FM_AL_DeactivateTitle"] = "Deactivate Attribute";
        ru["FM_AL_DeactivateMessage"] = "Атрибут используется в {0} категориях. При деактивации все привязки будут удалены. Продолжить?"; en["FM_AL_DeactivateMessage"] = "Attribute is used in {0} categories. Deactivating will remove all bindings. Continue?";
    }
}
