using SmartCon.Core.Services;

namespace SmartCon.UI;

public static class StringLocalization
{
    private static readonly Dictionary<string, string> Ru = new()
    {
        [Keys.Btn_Cancel] = "Отмена",
        [Keys.Btn_Connect] = "Соединить",
        [Keys.Btn_Insert] = "Вставить",
        [Keys.Btn_Change] = "Изменить",
        [Keys.Btn_Save] = "Сохранить",
        [Keys.Btn_Saved] = "✓ Сохранено",
        [Keys.Btn_Delete] = "Удалить",
        [Keys.Btn_Add] = "+ Добавить",
        [Keys.Btn_Import] = "Импорт…",
        [Keys.Btn_Export] = "Экспорт…",
        [Keys.Tip_Import] = "Загрузить настройки маппинга из JSON-файла (перезапишет текущие)",
        [Keys.Tip_Export] = "Сохранить настройки маппинга в JSON-файл",
        [Keys.Btn_Confirm] = "Подтвердить",
        [Keys.Btn_Close] = "Закрыть",
        [Keys.Btn_OK] = "OK",

        [Keys.Title_EditorSetup] = "Настройка соединения элементов",
        [Keys.Heading_EditorSetup] = "Настройка соединения элементов",
        [Keys.Title_Settings] = "Настройки SmartCon",
        [Keys.Title_FamilySelector] = "Выбор семейств фитингов",
        [Keys.Title_ConnType] = "Тип соединения",
        [Keys.Title_CtcSetup] = "Назначение типов коннекторов",
        [Keys.Title_About] = "О SmartCon",

        [Keys.Tip_RotateCCW] = "Повернуть против часовой стрелки",
        [Keys.Tip_RotationAngle] = "Угол поворота в градусах",
        [Keys.Tip_RotateCW] = "Повернуть по часовой стрелке",
        [Keys.Tip_AvailableSizes] = "Доступные типоразмеры динамического семейства",
        [Keys.Tip_ChangeSize] = "Изменить размер динамического семейства",
        [Keys.Tip_FittingCtc] = "Отразить типы коннекторов фитинга",
        [Keys.Tip_SelectFitting] = "Выберите фитинг для соединения",
        [Keys.Tip_InsertFitting] = "Вставить выбранный фитинг (примерка)",
        [Keys.Tip_ReducerCtc] = "Отразить типы коннекторов переходника",
        [Keys.Tip_SelectReducer] = "Выберите переходник",
        [Keys.Tip_InsertReducer] = "Вставить выбранный переходник",
        [Keys.Tip_ChainDecrement] = "Отсоединить последний уровень",
        [Keys.Tip_ChainIncrement] = "Присоединить следующий уровень",
        [Keys.Tip_ConnectAll] = "Подключить все элементы сети сразу",
        [Keys.Tip_SelectFittingFamilies] = "Нажмите для выбора семейств фитингов (недоступно при «Прямое» — используйте переходы сечения)",
        [Keys.Tip_SelectReducerFamilies] = "Нажмите для выбора семейств переходников",
        [Keys.Tip_ChangeConnection] = "Переключить на другой свободный коннектор",
        [Keys.Tip_Connect] = "Выполнить соединение элементов",

        [Keys.Label_Size] = "Размер:",
        [Keys.Label_Network] = "Сеть:",
        [Keys.Label_Updates] = "Обновления",
        [Keys.Label_AvailableFamilies] = "Доступные семейства:",
        [Keys.Label_FamilyFilter] = "(OST_PipeFitting, MultiPort, 2 коннектора)",
        [Keys.Label_SelectedFamilies] = "Выбранные (порядок = приоритет):",
        [Keys.Label_Family] = "Семейство: ",
        [Keys.Label_Symbol] = "Типоразмер: ",
        [Keys.Label_Connector] = "Коннектор ",

        [Keys.Btn_ChangeConnection] = "Изменить соединение",
        [Keys.Btn_ConnectAll] = "Подключить всё",
        [Keys.Btn_AddFamily] = "▶▶ Добавить",
        [Keys.Btn_RemoveFamily] = "◀◀ Убрать",
        [Keys.Btn_Up] = "▲ Вверх",
        [Keys.Btn_Down] = "▼ Вниз",
        [Keys.Btn_CheckUpdates] = "Проверить обновления",
        [Keys.Btn_DownloadInstall] = "Скачать и установить",
        [Keys.Chk_CheckOnStartup] = "Проверять при запуске",

        [Keys.Tab_ConnectorTypes] = "Типы коннекторов",
        [Keys.Tab_MappingRules] = "Правила маппинга",

        [Keys.Col_Code] = "Код",
        [Keys.Col_Name] = "Название",
        [Keys.Col_Description] = "Описание",
        [Keys.Col_ConnType1] = "Тип соединения 1",
        [Keys.Col_ConnType2] = "Тип соединения 2",
        [Keys.Col_Direct] = "Прямое",
        [Keys.Col_Fittings] = "Фитинги",
        [Keys.Col_Transitions] = "Переходы сечения",

        [Keys.Status_Active] = "Активно",
        [Keys.Status_Processing] = "Обработка…",
        [Keys.Status_SessionEnded] = "Сессия завершена",
        [Keys.Msg_AssignCtc] = "У фитинга не заданы типы коннекторов. Назначьте тип каждому коннектору:",

        [Keys.About_Author] = "Автор:",
        [Keys.About_Plugin] = "Плагин:",
        [Keys.About_PluginDesc] = "MEP коннектор труб для Revit 2025",
        [Keys.About_Repo] = "Репозиторий:",
        [Keys.About_Language] = "Язык:",

        [Keys.Mapping_NewType] = "Новый тип",
        [Keys.Mapping_NotSelected] = "(не выбраны)",
        [Keys.Fitting_DirectConnect] = "Без фитинга (прямое соединение)",
        [Keys.Fitting_TypeArrow] = "Тип {0} → {1}",

        [Keys.PM_Title_Settings] = "Настройки экспорта",
        [Keys.PM_Title_Progress] = "Экспорт проекта",
        [Keys.PM_Tab_General] = "Общие",
        [Keys.PM_Tab_Purge] = "Очистка",
        [Keys.PM_Tab_Views] = "Виды",
        [Keys.PM_Tab_Naming] = "Именование",
        [Keys.PM_CurrentFile] = "Текущий файл",
        [Keys.PM_FilePath] = "Путь:",
        [Keys.PM_Folder] = "Папка:",
        [Keys.PM_FileName] = "Имя:",
        [Keys.PM_SharedFolder] = "Папка Shared",
        [Keys.PM_Browse] = "Обзор...",
        [Keys.PM_SyncBefore] = "Синхронизировать перед экспортом",
        [Keys.PM_PurgeTitle] = "Выберите элементы для удаления из Shared-файла:",
        [Keys.PM_PurgeRvtLinks] = "RVT-связи",
        [Keys.PM_PurgeCadImports] = "CAD / IFC-связи",
        [Keys.PM_PurgeImages] = "Растровые изображения",
        [Keys.PM_PurgePointClouds] = "Облака точек",
        [Keys.PM_PurgeGroups] = "Группы (разгруппировать)",
        [Keys.PM_PurgeAssemblies] = "Сборки (разобрать)",
        [Keys.PM_PurgeSpaces] = "MEP-пространства",
        [Keys.PM_PurgeRebar] = "Арматура (Rebar)",
        [Keys.PM_PurgeFabric] = "Арматурные каркасы",
        [Keys.PM_PurgeSheets] = "Листы и чертежи",
        [Keys.PM_PurgeSchedules] = "Спецификации",
        [Keys.PM_PurgeUnused] = "Неиспользуемые элементы (Purge)",
        [Keys.PM_SelectAll] = "Все",
        [Keys.PM_DeselectAll] = "Ни одного",
        [Keys.PM_ViewsTitle] = "Виды для сохранения в Shared-файле:",
        [Keys.PM_RefreshViews] = "Обновить список",
        [Keys.PM_SearchViews] = "Поиск вида...",
        [Keys.PM_SelectedCount] = "Выбрано:",
        [Keys.PM_NamingTemplate] = "Шаблон имени файла",
        [Keys.PM_Blocks] = "Блоки имени:",
        [Keys.PM_ExportMappings] = "Маппинг экспорта:",
        [Keys.PM_Preview] = "Превью",
        [Keys.PM_Col_Index] = "№",
        [Keys.PM_Col_Field] = "Поле",
        [Keys.PM_Col_ParseRule] = "Правило парсинга",
        [Keys.PM_Col_Value] = "Значение",
        [Keys.PM_Col_Status] = "✓",
        [Keys.PM_Col_SourceValue] = "Исходное",
        [Keys.PM_Col_TargetValue] = "При экспорте",
        [Keys.PM_CurrentName] = "Текущее:",
        [Keys.PM_SharedName] = "Shared:",
        [Keys.PM_AddBlock] = "+ Добавить",
        [Keys.PM_RemoveBlock] = "- Удалить",
        [Keys.PM_MoveUp] = "Переместить вверх",
        [Keys.PM_MoveDown] = "Переместить вниз",
        [Keys.PM_AddMapping] = "+ Добавить",
        [Keys.PM_RemoveMapping] = "- Удалить",
        [Keys.PM_FieldLibrary] = "Библиотека полей...",
        [Keys.PM_Title_FieldLibrary] = "Библиотека полей",
        [Keys.PM_Col_FieldName] = "Имя поля",
        [Keys.PM_Col_DisplayName] = "Отображение",
        [Keys.PM_Col_Description] = "Описание",
        [Keys.PM_Col_Validation] = "Валидация",
        [Keys.PM_Col_Min] = "Мин",
        [Keys.PM_Col_Max] = "Макс",
        [Keys.PM_AllowedValuesButton] = "Допустимые значения...",
        [Keys.PM_DuplicateField] = "Дублировать",
        [Keys.PM_ValidField] = "\u2713",
        [Keys.PM_InvalidField] = "\u2717",
        [Keys.PM_AddField] = "+ Добавить",
        [Keys.PM_RemoveField] = "- Удалить",
        [Keys.PM_Title_AllowedValues] = "Допустимые значения",
        [Keys.PM_Title_ParseRule] = "Правило парсинга",
        [Keys.PM_ValidationMode] = "Режим валидации:",
        [Keys.PM_MinLength] = "Мин. длина:",
        [Keys.PM_MaxLength] = "Макс. длина:",
        [Keys.PM_AddValue] = "+ Добавить",
        [Keys.PM_RemoveValue] = "- Удалить",
        [Keys.PM_ParseMode] = "Режим:",
        [Keys.PM_Delimiter] = "Разделитель:",
        [Keys.PM_SegmentIndex] = "Сегмент:",
        [Keys.PM_SegmentCount] = "Кол-во:",
        [Keys.PM_CharCount] = "Кол-во симв.:",
        [Keys.PM_OpenMarker] = "Откр.:",
        [Keys.PM_CloseMarker] = "Закр.:",
        [Keys.PM_Marker] = "Маркер:",
        [Keys.PM_CharOffset] = "Пропуск:",
        [Keys.PM_MarkerIndex] = "№ символа:",
        [Keys.PM_Result] = "Результат:",
        [Keys.PM_Remaining] = "Остаток:",
        [Keys.PM_ExportName_CurrentLabel] = "Текущее имя: ",
        [Keys.PM_ExportName_FillFields] = "Заполните поля для имени экспорта:",
        [Keys.PM_ExportName_Preview] = "Предпросмотр: ",

        [Keys.FM_SearchPlaceholder] = "Поиск семейств...",
        [Keys.FM_Import] = "Импорт",
        [Keys.FM_ImportFile] = "Импорт файла",
        [Keys.FM_ImportFolder] = "Импорт папки",
        [Keys.FM_LoadToProject] = "Загрузить в проект",
        [Keys.FM_LoadAndPlace] = "Загрузить и разместить",
        [Keys.FM_ExtractTypes] = "Извлечь типоразмеры",
        [Keys.FM_ImportData] = "Импорт данных",
        [Keys.FM_PlaceType] = "Разместить тип",
        [Keys.FM_EditMetadata] = "Редактировать",
        [Keys.FM_NoActiveDocument] = "Нет активного документа",
        [Keys.FM_ImportProgress] = "Импорт {0} из {1}...",
        [Keys.FM_ColName] = "Имя",
        [Keys.FM_ColStatus] = "Статус",
        [Keys.FM_ColVersion] = "Версия",
        [Keys.FM_ColUpdated] = "Обновлено",
        [Keys.FM_Save] = "Сохранить",
        [Keys.FM_Cancel] = "Отмена",
        [Keys.FM_Name] = "Имя",
        [Keys.FM_Description] = "Описание",
        [Keys.FM_Category] = "Категория",
        [Keys.FM_Tags] = "Теги (через запятую)",
        [Keys.FM_Status] = "Статус",
        [Keys.FM_ImportSuccess] = "Импортировано: {0}",
        [Keys.FM_ImportError] = "Ошибка импорта: {0}",
        [Keys.FM_ImportPrepareError] = "Ошибка подготовки",
        [Keys.FM_FamilyFileNotFound] = "Файл семейства не найден",
        [Keys.FM_ImportResultFormat] = "Импортировано: {0} типоразмеров, {1} значений найдено",
        [Keys.FM_ImportDataError] = "Ошибка импорта: {0}",
        [Keys.FM_ImportFileToCategory] = "Импорт файла",
        [Keys.FM_ImportFolderToCategory] = "Импорт папки",
        [Keys.FM_ImportDataForCategory] = "Импорт данных",
        [Keys.FM_ImportDataProgress] = "Обработка {0} из {1}: {2}",
        [Keys.FM_NoFamiliesInCategory] = "В категории нет семейств",
        [Keys.FM_LoadSuccess] = "Семейство \"{0}\" загружено в проект",
        [Keys.FM_LoadAndPlaceSuccess] = "Семейство \"{0}\" — нажмите для размещения",
        [Keys.FM_LoadError] = "Ошибка загрузки: {0}",
        [Keys.FM_DuplicateSkipped] = "Дубликат пропущен: {0}",
        [Keys.FM_Title_MetadataEdit] = "Редактирование метаданных",

        [Keys.FM_DbSwitched] = "База данных переключена на: {0}",
        [Keys.FM_DbSwitchError] = "Ошибка переключения базы данных",
        [Keys.FM_DbCreated] = "База данных \"{0}\" создана",
        [Keys.FM_DbCreateError] = "Ошибка создания БД: {0}",
        [Keys.FM_DbDeleted] = "База данных \"{0}\" удалена",
        [Keys.FM_DbDeleteError] = "Ошибка удаления БД: {0}",
        [Keys.FM_DbDeleteSingle] = "Нельзя удалить единственную базу данных.",
        [Keys.FM_DbDeleteTitle] = "Удаление базы данных",
        [Keys.FM_DbDeletePrompt] = "Введите \"{0}\" для подтверждения удаления:",
        [Keys.FM_DbNewTitle] = "Новая база данных",
        [Keys.FM_DbNewPrompt] = "Введите название новой базы данных:",
        [Keys.FM_DbNewDefault] = "Новый каталог",
        [Keys.FM_FamilyDeleted] = "Семейство \"{0}\" удалено из каталога",
        [Keys.FM_FamilyDeleteError] = "Ошибка удаления семейства",
        [Keys.FM_FamilyDeleteTitle] = "Удаление семейства",
        [Keys.FM_FamilyDeletePrompt] = "Удалить семейство \"{0}\" из каталога?",
        [Keys.FM_DeleteFromCatalog] = "Удалить из каталога",
        [Keys.FM_NoVersionSelected] = "Версия не выбрана",
        [Keys.FM_NoCategory] = "Без категории",
        [Keys.FM_DbSelectPath] = "Выберите расположение базы данных",
        [Keys.FM_Disconnect] = "Отключить базу данных",

        [Keys.FM_Update] = "Обновить",
        [Keys.FM_UpdateSuccess] = "Обновлено: {0} → {1}",
        [Keys.FM_UpdateIdentical] = "Файл идентичен текущей версии: {0}",
        [Keys.FM_UpdateError] = "Ошибка обновления: {0}",

        [Keys.FM_CTE_Title] = "Редактор дерева категорий",
        [Keys.FM_CTE_AddRoot] = "+ Корень",
        [Keys.FM_CTE_AddChild] = "+ Вложенная",
        [Keys.FM_CTE_Rename] = "Переименовать",
        [Keys.FM_CTE_Delete] = "Удалить",
        [Keys.FM_CTE_Import] = "Импорт",
        [Keys.FM_CTE_Export] = "Экспорт",
        [Keys.FM_CTE_Close] = "Закрыть",
        [Keys.FM_CTE_AddCategory] = "Добавить категорию",
        [Keys.FM_CTE_CategoryName] = "Название категории:",
        [Keys.FM_CTE_AddSubcategory] = "Добавить подкатегорию",
        [Keys.FM_CTE_SubcategoryName] = "Название подкатегории:",
        [Keys.FM_CTE_NewName] = "Новое название:",
        [Keys.FM_CTE_DeleteCategory] = "Удаление категории",
        [Keys.FM_CTE_DeleteConfirm] = "Удалить \"{0}\"? {1} семейств будут перемещены в \"{2}\".",
        [Keys.FM_CTE_DeleteEmpty] = "Удалить \"{0}\"?",
        [Keys.FM_CTE_Deleted] = "Удалено: {0}",
        [Keys.FM_CTE_Saved] = "Сохранено",
        [Keys.FM_CTE_ImportTree] = "Импорт дерева категорий",
        [Keys.FM_CTE_Imported] = "Импортировано {0} категорий",
        [Keys.FM_CTE_ExportTree] = "Экспорт дерева категорий",
        [Keys.FM_CTE_Exported] = "Экспортировано в {0}",
        [Keys.FM_CTE_AttrExists] = "Атрибут \"{0}\" уже существует.",
        [Keys.FM_CTE_ExportAttrs] = "Экспорт атрибутов",
        [Keys.FM_CTE_ExportFull] = "Экспорт полного пакета",
        [Keys.FM_CTE_CategoriesAndAttrs] = "Категории и атрибуты",
        [Keys.FM_CTE_CategoryTree] = "Дерево категорий",
        [Keys.FM_CTE_AttributesFor] = "Атрибуты:",
        [Keys.FM_CTE_SelectCategory] = "Выберите категорию",
        [Keys.FM_CTE_SelectCategoryHint] = "Выберите категорию для управления атрибутами",
        [Keys.FM_CTE_AllGroups] = "Все атрибуты",
        [Keys.FM_CTE_SearchAttrs] = "Поиск атрибутов...",
        [Keys.FM_CTE_Inherited] = "(наследован)",
        [Keys.FM_CTE_NewAttrName] = "Новый атрибут",
        [Keys.FM_CTE_AddAttr] = "Добавить",
        [Keys.FM_CTE_AttrLibrary] = "Библиотека атрибутов...",
        [Keys.FM_CTE_ImportJson] = "Импорт из JSON",
        [Keys.FM_CTE_UnsavedChangesTitle] = "Несохранённые изменения",
        [Keys.FM_CTE_UnsavedChangesMessage] = "У вас есть несохранённые изменения. Сохранить перед закрытием?",
        [Keys.FM_CTE_ExportColon] = "Экспорт:",
        [Keys.FM_CP_Title] = "Выбор категории",
        [Keys.FM_CP_Clear] = "Сбросить",

        [Keys.FM_Tip_CreateDb] = "Создать новую базу данных",
        [Keys.FM_Tip_ConnectDb] = "Подключить существующую базу данных",
        [Keys.FM_Tip_EditCategories] = "Редактировать категории",

        [Keys.FM_Properties] = "Свойства",
        [Keys.FM_Props_SelectImage] = "Выберите изображение",
        [Keys.FM_Props_AddFile] = "Выберите файл",
        [Keys.FM_Tab_General] = "Общие",
        [Keys.FM_Tab_Content] = "Контент",
        [Keys.FM_Tab_Attributes] = "Атрибуты",
        [Keys.FM_Tab_3DView] = "3D Просмотр",
        [Keys.FM_Props_Manufacturer] = "Производитель",
        [Keys.FM_Props_Version] = "Версия",
        [Keys.FM_Props_Size] = "Размер",
        [Keys.FM_Props_Created] = "Создано",
        [Keys.FM_Props_Updated] = "Обновлено",
        [Keys.FM_Props_NoAvatar] = "Нет изображения",
        [Keys.FM_Props_ChangeImage] = "Сменить",
        [Keys.FM_Props_RemoveImage] = "Удалить",
        [Keys.FM_Props_Images] = "Изображения",
        [Keys.FM_Props_Videos] = "Видео",
        [Keys.FM_Props_Documents] = "Документы",
        [Keys.FM_Props_LookupTables] = "Таблицы поиска (CSV)",
        [Keys.FM_Props_Spreadsheets] = "Электронные таблицы (XLS)",
        [Keys.FM_Props_Models3D] = "3D Модели",
        [Keys.FM_Props_Other] = "Прочие файлы",
        [Keys.FM_Props_Open] = "Открыть",
        [Keys.FM_Props_Delete] = "Удалить",
        [Keys.FM_Props_SetPrimary] = "Сделать главной",
        [Keys.FM_Props_Add] = "+ Добавить",
        [Keys.FM_Props_NoAttributes] = "Атрибуты не извлечены",
        [Keys.FM_Props_NoAttributesDesc] = "Для извлечения атрибутов семейство будет временно загружено в Revit",
        [Keys.FM_Props_PresetCategory] = "Категория: {0}",
        [Keys.FM_Props_NoPresets] = "Нет пресетов для этой категории",
        [Keys.FM_Props_3DComingSoon] = "3D-просмотр модели (GLB) — в разработке",
        [Keys.FM_Props_3DDesc] = "Здесь будет интерактивный 3D-просмотр модели семейства. Вы сможете вращать, масштабировать и изучать геометрию перед загрузкой в проект.",
        [Keys.FM_Props_FileInfo] = "Информация о файле",
        [Keys.FM_Props_Title] = "Свойства семейства",
        [Keys.FM_Props_NoAssets] = "Нет файлов",
        [Keys.FM_Props_ConfigurePreset] = "Настроить пресет...",
        [Keys.FM_Props_ExtractAttributes] = "Извлечь атрибуты",
        [Keys.FM_PE_Title] = "Редактор пресета атрибутов",
        [Keys.FM_PE_ParameterName] = "Имя параметра",
        [Keys.FM_PE_DisplayName] = "Отображаемое имя",
        [Keys.FM_PE_AddParameter] = "+ Добавить параметр",
        [Keys.FM_PE_RemoveParameter] = "- Удалить",
        [Keys.FM_Props_XlsNote] = "XLS — рабочий файл, CSV — для Revit Lookup Table",

        [Keys.FM_Props_NoCategoryAttr] = "Семейству не назначена категория. Назначьте категорию, чтобы определить обязательные атрибуты.",
        [Keys.FM_Props_NoBindingsAttr] = "Для категории нет обязательных атрибутов.",
        [Keys.FM_Props_NotImported] = "Атрибуты ещё не импортированы",
        [Keys.FM_Props_NotImportedDesc] = "Используйте команду «Импорт данных» из контекстного меню семейства в основной панели.",
        [Keys.FM_Props_Completeness] = "Полнота",
        [Keys.FM_Props_TypeSize] = "Типоразмер",

        [Keys.FM_FamilyNotFoundAfterLoad] = "Семейство не найдено после загрузки",
        [Keys.FM_CannotDisconnectOnlyDatabase] = "Нельзя отключить единственную базу данных.",
        [Keys.FM_ErrorFormat] = "Ошибка: {0}",

        [Keys.FM_AL_Title] = "Библиотека атрибутов",
        [Keys.FM_AL_Search] = "Поиск атрибутов...",
        [Keys.FM_AL_Name] = "Имя",
        [Keys.FM_AL_Group] = "Группа",
        [Keys.FM_AL_Active] = "Активен",
        [Keys.FM_AL_UsedIn] = "Используется в",
        [Keys.FM_AL_Delete] = "Удалить",
        [Keys.FM_AL_Close] = "Закрыть",
        [Keys.FM_AL_ConfirmDelete] = "Удалить атрибут \"{0}\"? Он используется в {1} категориях.",
        [Keys.FM_AL_ConfirmDeleteEmpty] = "Удалить атрибут \"{0}\"?",
        [Keys.FM_AL_Add] = "Добавить",
        [Keys.FM_AL_Rename] = "Переименовать",
        [Keys.FM_AL_SetGroup] = "Группа",
        [Keys.FM_AL_EnterName] = "Имя атрибута:",
        [Keys.FM_AL_EnterGroup] = "Имя группы:",

        [Keys.Btn_Yes] = "Да",
        [Keys.Btn_No] = "Нет",
        [Keys.FM_CTE_ContextMenu_Rename] = "Переименовать",
        [Keys.FM_CTE_ContextMenu_AddChild] = "Добавить подкатегорию",
        [Keys.FM_CTE_ContextMenu_Delete] = "Удалить",
        [Keys.FM_CTE_NewCategory] = "Новая категория",
        [Keys.FM_CTE_Attributes] = "Атрибуты",
        [Keys.FM_AL_DeactivateTitle] = "Деактивация атрибута",
        [Keys.FM_AL_DeactivateMessage] = "Атрибут используется в {0} категориях. При деактивации все привязки будут удалены. Продолжить?",
        [Keys.FM_Confirm_Title] = "Подтверждение",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        [Keys.Btn_Cancel] = "Cancel",
        [Keys.Btn_Connect] = "Connect",
        [Keys.Btn_Insert] = "Insert",
        [Keys.Btn_Change] = "Change",
        [Keys.Btn_Save] = "Save",
        [Keys.Btn_Saved] = "✓ Saved",
        [Keys.Btn_Delete] = "Delete",
        [Keys.Btn_Add] = "+ Add",
        [Keys.Btn_Import] = "Import…",
        [Keys.Btn_Export] = "Export…",
        [Keys.Tip_Import] = "Load mapping settings from a JSON file (overwrites current)",
        [Keys.Tip_Export] = "Save mapping settings to a JSON file",
        [Keys.Btn_Confirm] = "Confirm",
        [Keys.Btn_Close] = "Close",
        [Keys.Btn_OK] = "OK",

        [Keys.Title_EditorSetup] = "Connection Setup",
        [Keys.Heading_EditorSetup] = "Connection Setup",
        [Keys.Title_Settings] = "SmartCon Settings",
        [Keys.Title_FamilySelector] = "Select Fitting Families",
        [Keys.Title_ConnType] = "Connection Type",
        [Keys.Title_CtcSetup] = "Assign Connector Types",
        [Keys.Title_About] = "About SmartCon",

        [Keys.Tip_RotateCCW] = "Rotate counter-clockwise",
        [Keys.Tip_RotationAngle] = "Rotation angle in degrees",
        [Keys.Tip_RotateCW] = "Rotate clockwise",
        [Keys.Tip_AvailableSizes] = "Available dynamic family sizes",
        [Keys.Tip_ChangeSize] = "Change dynamic family size",
        [Keys.Tip_FittingCtc] = "Reflect fitting connector types",
        [Keys.Tip_SelectFitting] = "Select fitting for connection",
        [Keys.Tip_InsertFitting] = "Insert selected fitting (preview)",
        [Keys.Tip_ReducerCtc] = "Reflect reducer connector types",
        [Keys.Tip_SelectReducer] = "Select reducer",
        [Keys.Tip_InsertReducer] = "Insert selected reducer",
        [Keys.Tip_ChainDecrement] = "Disconnect last level",
        [Keys.Tip_ChainIncrement] = "Connect next level",
        [Keys.Tip_ConnectAll] = "Connect all network elements at once",
        [Keys.Tip_SelectFittingFamilies] = "Click to select fitting families (unavailable for Direct — use cross-section transitions)",
        [Keys.Tip_SelectReducerFamilies] = "Click to select reducer families",
        [Keys.Tip_ChangeConnection] = "Switch to another free connector",
        [Keys.Tip_Connect] = "Execute element connection",

        [Keys.Label_Size] = "Size:",
        [Keys.Label_Network] = "Network:",
        [Keys.Label_Updates] = "Updates",
        [Keys.Label_AvailableFamilies] = "Available families:",
        [Keys.Label_FamilyFilter] = "(OST_PipeFitting, MultiPort, 2 connectors)",
        [Keys.Label_SelectedFamilies] = "Selected (order = priority):",
        [Keys.Label_Family] = "Family: ",
        [Keys.Label_Symbol] = "Type: ",
        [Keys.Label_Connector] = "Connector ",

        [Keys.Btn_ChangeConnection] = "Change connection",
        [Keys.Btn_ConnectAll] = "Connect all",
        [Keys.Btn_AddFamily] = "▶▶ Add",
        [Keys.Btn_RemoveFamily] = "◀◀ Remove",
        [Keys.Btn_Up] = "▲ Up",
        [Keys.Btn_Down] = "▼ Down",
        [Keys.Btn_CheckUpdates] = "Check for updates",
        [Keys.Btn_DownloadInstall] = "Download and install",
        [Keys.Chk_CheckOnStartup] = "Check on startup",

        [Keys.Tab_ConnectorTypes] = "Connector Types",
        [Keys.Tab_MappingRules] = "Mapping Rules",

        [Keys.Col_Code] = "Code",
        [Keys.Col_Name] = "Name",
        [Keys.Col_Description] = "Description",
        [Keys.Col_ConnType1] = "Connection Type 1",
        [Keys.Col_ConnType2] = "Connection Type 2",
        [Keys.Col_Direct] = "Direct",
        [Keys.Col_Fittings] = "Fittings",
        [Keys.Col_Transitions] = "Cross-Section Transitions",

        [Keys.Status_Active] = "Active",
        [Keys.Status_Processing] = "Processing…",
        [Keys.Status_SessionEnded] = "Session ended",
        [Keys.Msg_AssignCtc] = "Fitting has no connector types assigned. Assign a type to each connector:",

        [Keys.About_Author] = "Author:",
        [Keys.About_Plugin] = "Plugin:",
        [Keys.About_PluginDesc] = "MEP Pipe Connector for Revit 2025",
        [Keys.About_Repo] = "Repo:",
        [Keys.About_Language] = "Language:",

        [Keys.Mapping_NewType] = "New type",
        [Keys.Mapping_NotSelected] = "(not selected)",
        [Keys.Fitting_DirectConnect] = "No fitting (direct connect)",
        [Keys.Fitting_TypeArrow] = "Type {0} → {1}",

        [Keys.PM_Title_Settings] = "Export Settings",
        [Keys.PM_Title_Progress] = "Exporting Project",
        [Keys.PM_Tab_General] = "General",
        [Keys.PM_Tab_Purge] = "Purge",
        [Keys.PM_Tab_Views] = "Views",
        [Keys.PM_Tab_Naming] = "Naming",
        [Keys.PM_CurrentFile] = "Current File",
        [Keys.PM_FilePath] = "Path:",
        [Keys.PM_Folder] = "Folder:",
        [Keys.PM_FileName] = "Name:",
        [Keys.PM_SharedFolder] = "Shared Folder",
        [Keys.PM_Browse] = "Browse...",
        [Keys.PM_SyncBefore] = "Synchronize before export",
        [Keys.PM_PurgeTitle] = "Select elements to remove from the Shared file:",
        [Keys.PM_PurgeRvtLinks] = "RVT Links",
        [Keys.PM_PurgeCadImports] = "CAD / IFC Links",
        [Keys.PM_PurgeImages] = "Raster Images",
        [Keys.PM_PurgePointClouds] = "Point Clouds",
        [Keys.PM_PurgeGroups] = "Groups (ungroup)",
        [Keys.PM_PurgeAssemblies] = "Assemblies (disassemble)",
        [Keys.PM_PurgeSpaces] = "MEP Spaces",
        [Keys.PM_PurgeRebar] = "Rebar",
        [Keys.PM_PurgeFabric] = "Fabric Reinforcement",
        [Keys.PM_PurgeSheets] = "Sheets and Drawings",
        [Keys.PM_PurgeSchedules] = "Schedules",
        [Keys.PM_PurgeUnused] = "Unused Elements (Purge)",
        [Keys.PM_SelectAll] = "All",
        [Keys.PM_DeselectAll] = "None",
        [Keys.PM_ViewsTitle] = "Views to keep in the Shared file:",
        [Keys.PM_RefreshViews] = "Refresh List",
        [Keys.PM_SearchViews] = "Search views...",
        [Keys.PM_SelectedCount] = "Selected:",
        [Keys.PM_NamingTemplate] = "File Name Template",
        [Keys.PM_Blocks] = "Name Blocks:",
        [Keys.PM_ExportMappings] = "Export Mapping:",
        [Keys.PM_Preview] = "Preview",
        [Keys.PM_Col_Index] = "#",
        [Keys.PM_Col_Field] = "Field",
        [Keys.PM_Col_ParseRule] = "Parse Rule",
        [Keys.PM_Col_Value] = "Value",
        [Keys.PM_Col_Status] = "✓",
        [Keys.PM_Col_SourceValue] = "Source",
        [Keys.PM_Col_TargetValue] = "Export",
        [Keys.PM_CurrentName] = "Current:",
        [Keys.PM_SharedName] = "Shared:",
        [Keys.PM_AddBlock] = "+ Add",
        [Keys.PM_RemoveBlock] = "- Remove",
        [Keys.PM_MoveUp] = "Move up",
        [Keys.PM_MoveDown] = "Move down",
        [Keys.PM_AddMapping] = "+ Add",
        [Keys.PM_RemoveMapping] = "- Remove",
        [Keys.PM_FieldLibrary] = "Field Library...",
        [Keys.PM_Title_FieldLibrary] = "Field Library",
        [Keys.PM_Col_FieldName] = "Field Name",
        [Keys.PM_Col_DisplayName] = "Display Name",
        [Keys.PM_Col_Description] = "Description",
        [Keys.PM_Col_Validation] = "Validation",
        [Keys.PM_Col_Min] = "Min",
        [Keys.PM_Col_Max] = "Max",
        [Keys.PM_AllowedValuesButton] = "Allowed Values...",
        [Keys.PM_DuplicateField] = "Duplicate",
        [Keys.PM_ValidField] = "\u2713",
        [Keys.PM_InvalidField] = "\u2717",
        [Keys.PM_AddField] = "+ Add",
        [Keys.PM_RemoveField] = "- Remove",
        [Keys.PM_Title_AllowedValues] = "Allowed Values",
        [Keys.PM_Title_ParseRule] = "Parse Rule",
        [Keys.PM_ValidationMode] = "Validation mode:",
        [Keys.PM_MinLength] = "Min length:",
        [Keys.PM_MaxLength] = "Max length:",
        [Keys.PM_AddValue] = "+ Add",
        [Keys.PM_RemoveValue] = "- Remove",
        [Keys.PM_ParseMode] = "Mode:",
        [Keys.PM_Delimiter] = "Delimiter:",
        [Keys.PM_SegmentIndex] = "Segment:",
        [Keys.PM_SegmentCount] = "Count:",
        [Keys.PM_CharCount] = "Char count:",
        [Keys.PM_OpenMarker] = "Open:",
        [Keys.PM_CloseMarker] = "Close:",
        [Keys.PM_Marker] = "Marker:",
        [Keys.PM_CharOffset] = "Skip:",
        [Keys.PM_MarkerIndex] = "Symbol #:",
        [Keys.PM_Result] = "Result:",
        [Keys.PM_Remaining] = "Remaining:",
        [Keys.PM_ExportName_CurrentLabel] = "Current name: ",
        [Keys.PM_ExportName_FillFields] = "Fill fields for export name:",
        [Keys.PM_ExportName_Preview] = "Preview: ",

        [Keys.FM_SearchPlaceholder] = "Search families...",
        [Keys.FM_Import] = "Import",
        [Keys.FM_ImportFile] = "Import File",
        [Keys.FM_ImportFolder] = "Import Folder",
        [Keys.FM_LoadToProject] = "Load to Project",
        [Keys.FM_LoadAndPlace] = "Load and Place",
        [Keys.FM_ExtractTypes] = "Extract Types",
        [Keys.FM_ImportData] = "Import Data",
        [Keys.FM_PlaceType] = "Place Type",
        [Keys.FM_EditMetadata] = "Edit",
        [Keys.FM_NoActiveDocument] = "No active document",
        [Keys.FM_ImportProgress] = "Importing {0} of {1}...",
        [Keys.FM_ColName] = "Name",
        [Keys.FM_ColStatus] = "Status",
        [Keys.FM_ColVersion] = "Version",
        [Keys.FM_ColUpdated] = "Updated",
        [Keys.FM_Save] = "Save",
        [Keys.FM_Cancel] = "Cancel",
        [Keys.FM_Name] = "Name",
        [Keys.FM_Description] = "Description",
        [Keys.FM_Category] = "Category",
        [Keys.FM_Tags] = "Tags (comma-separated)",
        [Keys.FM_Status] = "Status",
        [Keys.FM_ImportSuccess] = "Imported: {0}",
        [Keys.FM_ImportError] = "Import error: {0}",
        [Keys.FM_ImportPrepareError] = "Preparation error",
        [Keys.FM_FamilyFileNotFound] = "Family file not found",
        [Keys.FM_ImportResultFormat] = "Imported: {0} types, {1} values found",
        [Keys.FM_ImportDataError] = "Import error: {0}",
        [Keys.FM_ImportFileToCategory] = "Import file",
        [Keys.FM_ImportFolderToCategory] = "Import folder",
        [Keys.FM_ImportDataForCategory] = "Import data",
        [Keys.FM_ImportDataProgress] = "Processing {0} of {1}: {2}",
        [Keys.FM_NoFamiliesInCategory] = "No families in category",
        [Keys.FM_LoadSuccess] = "Family \"{0}\" loaded into project",
        [Keys.FM_LoadAndPlaceSuccess] = "Family \"{0}\" — click to place",
        [Keys.FM_LoadError] = "Load error: {0}",
        [Keys.FM_DuplicateSkipped] = "Duplicate skipped: {0}",
        [Keys.FM_Title_MetadataEdit] = "Edit Metadata",

        [Keys.FM_DbSwitched] = "Database switched to: {0}",
        [Keys.FM_DbSwitchError] = "Error switching database",
        [Keys.FM_DbCreated] = "Database \"{0}\" created",
        [Keys.FM_DbCreateError] = "Error creating database: {0}",
        [Keys.FM_DbDeleted] = "Database \"{0}\" deleted",
        [Keys.FM_DbDeleteError] = "Error deleting database: {0}",
        [Keys.FM_DbDeleteSingle] = "Cannot delete the only database.",
        [Keys.FM_DbDeleteTitle] = "Delete Database",
        [Keys.FM_DbDeletePrompt] = "Enter \"{0}\" to confirm deletion:",
        [Keys.FM_DbNewTitle] = "New Database",
        [Keys.FM_DbNewPrompt] = "Enter new database name:",
        [Keys.FM_DbNewDefault] = "New Catalog",
        [Keys.FM_FamilyDeleted] = "Family \"{0}\" deleted from catalog",
        [Keys.FM_FamilyDeleteError] = "Error deleting family",
        [Keys.FM_FamilyDeleteTitle] = "Delete Family",
        [Keys.FM_FamilyDeletePrompt] = "Delete family \"{0}\" from catalog?",
        [Keys.FM_DeleteFromCatalog] = "Delete from catalog",
        [Keys.FM_NoVersionSelected] = "No version selected",
        [Keys.FM_NoCategory] = "No category",
        [Keys.FM_DbSelectPath] = "Select database location",
        [Keys.FM_Disconnect] = "Disconnect database",

        [Keys.FM_Update] = "Update",
        [Keys.FM_UpdateSuccess] = "Updated: {0} → {1}",
        [Keys.FM_UpdateIdentical] = "File is identical to current version: {0}",
        [Keys.FM_UpdateError] = "Update error: {0}",

        [Keys.FM_CTE_Title] = "Category Tree Editor",
        [Keys.FM_CTE_AddRoot] = "+ Root",
        [Keys.FM_CTE_AddChild] = "+ Child",
        [Keys.FM_CTE_Rename] = "Rename",
        [Keys.FM_CTE_Delete] = "Delete",
        [Keys.FM_CTE_Import] = "Import",
        [Keys.FM_CTE_Export] = "Export",
        [Keys.FM_CTE_Close] = "Close",
        [Keys.FM_CTE_AddCategory] = "Add Category",
        [Keys.FM_CTE_CategoryName] = "Category name:",
        [Keys.FM_CTE_AddSubcategory] = "Add Subcategory",
        [Keys.FM_CTE_SubcategoryName] = "Subcategory name:",
        [Keys.FM_CTE_NewName] = "New name:",
        [Keys.FM_CTE_DeleteCategory] = "Delete Category",
        [Keys.FM_CTE_DeleteConfirm] = "Delete \"{0}\"? {1} families will be moved to \"{2}\".",
        [Keys.FM_CTE_DeleteEmpty] = "Delete \"{0}\"?",
        [Keys.FM_CTE_Deleted] = "Deleted: {0}",
        [Keys.FM_CTE_Saved] = "Saved",
        [Keys.FM_CTE_ImportTree] = "Import Category Tree",
        [Keys.FM_CTE_Imported] = "Imported {0} categories",
        [Keys.FM_CTE_ExportTree] = "Export Category Tree",
        [Keys.FM_CTE_Exported] = "Exported to {0}",
        [Keys.FM_CTE_AttrExists] = "Attribute \"{0}\" already exists.",
        [Keys.FM_CTE_ExportAttrs] = "Export Attributes",
        [Keys.FM_CTE_ExportFull] = "Export Full Package",
        [Keys.FM_CTE_CategoriesAndAttrs] = "Categories & Attributes",
        [Keys.FM_CTE_CategoryTree] = "Category Tree",
        [Keys.FM_CTE_AttributesFor] = "Attributes:",
        [Keys.FM_CTE_SelectCategory] = "Select a category",
        [Keys.FM_CTE_SelectCategoryHint] = "Select a category to manage attributes",
        [Keys.FM_CTE_AllGroups] = "All attributes",
        [Keys.FM_CTE_SearchAttrs] = "Search attributes...",
        [Keys.FM_CTE_Inherited] = "(inherited)",
        [Keys.FM_CTE_NewAttrName] = "New attribute",
        [Keys.FM_CTE_AddAttr] = "Add",
        [Keys.FM_CTE_AttrLibrary] = "Attribute Library...",
        [Keys.FM_CTE_ImportJson] = "Import JSON",
        [Keys.FM_CTE_UnsavedChangesTitle] = "Unsaved Changes",
        [Keys.FM_CTE_UnsavedChangesMessage] = "You have unsaved changes. Save before closing?",
        [Keys.FM_CTE_ExportColon] = "Export:",
        [Keys.FM_CP_Title] = "Select Category",
        [Keys.FM_CP_Clear] = "Clear",

        [Keys.FM_Tip_CreateDb] = "Create new database",
        [Keys.FM_Tip_ConnectDb] = "Connect existing database",
        [Keys.FM_Tip_EditCategories] = "Edit categories",

        [Keys.FM_Properties] = "Properties",
        [Keys.FM_Props_SelectImage] = "Select image",
        [Keys.FM_Props_AddFile] = "Select file",
        [Keys.FM_Tab_General] = "General",
        [Keys.FM_Tab_Content] = "Content",
        [Keys.FM_Tab_Attributes] = "Attributes",
        [Keys.FM_Tab_3DView] = "3D Preview",
        [Keys.FM_Props_Manufacturer] = "Manufacturer",
        [Keys.FM_Props_Version] = "Version",
        [Keys.FM_Props_Size] = "Size",
        [Keys.FM_Props_Created] = "Created",
        [Keys.FM_Props_Updated] = "Updated",
        [Keys.FM_Props_NoAvatar] = "No image",
        [Keys.FM_Props_ChangeImage] = "Change",
        [Keys.FM_Props_RemoveImage] = "Remove",
        [Keys.FM_Props_Images] = "Images",
        [Keys.FM_Props_Videos] = "Videos",
        [Keys.FM_Props_Documents] = "Documents",
        [Keys.FM_Props_LookupTables] = "Lookup Tables (CSV)",
        [Keys.FM_Props_Spreadsheets] = "Spreadsheets (XLS)",
        [Keys.FM_Props_Models3D] = "3D Models",
        [Keys.FM_Props_Other] = "Other Files",
        [Keys.FM_Props_Open] = "Open",
        [Keys.FM_Props_Delete] = "Delete",
        [Keys.FM_Props_SetPrimary] = "Set as primary",
        [Keys.FM_Props_Add] = "+ Add",
        [Keys.FM_Props_NoAttributes] = "No attributes extracted",
        [Keys.FM_Props_NoAttributesDesc] = "To extract attributes, the family will be temporarily loaded into Revit",
        [Keys.FM_Props_PresetCategory] = "Category: {0}",
        [Keys.FM_Props_NoPresets] = "No presets for this category",
        [Keys.FM_Props_3DComingSoon] = "3D model preview (GLB) — coming soon",
        [Keys.FM_Props_3DDesc] = "Interactive 3D preview of the family model will be available here. You will be able to rotate, zoom, and explore geometry before loading into the project.",
        [Keys.FM_Props_FileInfo] = "File Information",
        [Keys.FM_Props_Title] = "Family Properties",
        [Keys.FM_Props_NoAssets] = "No files",
        [Keys.FM_Props_ConfigurePreset] = "Configure preset...",
        [Keys.FM_Props_ExtractAttributes] = "Extract attributes",
        [Keys.FM_PE_Title] = "Attribute Preset Editor",
        [Keys.FM_PE_ParameterName] = "Parameter Name",
        [Keys.FM_PE_DisplayName] = "Display Name",
        [Keys.FM_PE_AddParameter] = "+ Add parameter",
        [Keys.FM_PE_RemoveParameter] = "- Remove",
        [Keys.FM_Props_XlsNote] = "XLS — working file, CSV — for Revit Lookup Table",

        [Keys.FM_Props_NoCategoryAttr] = "No category assigned. Assign a category to define required attributes.",
        [Keys.FM_Props_NoBindingsAttr] = "No required attributes for this category.",
        [Keys.FM_Props_NotImported] = "Attributes not yet imported",
        [Keys.FM_Props_NotImportedDesc] = "Use the 'Import Data' command from the family's context menu in the main panel.",
        [Keys.FM_Props_Completeness] = "Completeness",
        [Keys.FM_Props_TypeSize] = "Type",

        [Keys.FM_FamilyNotFoundAfterLoad] = "Family not found after loading",
        [Keys.FM_CannotDisconnectOnlyDatabase] = "Cannot disconnect the only database.",
        [Keys.FM_ErrorFormat] = "Error: {0}",

        [Keys.FM_AL_Title] = "Attribute Library",
        [Keys.FM_AL_Search] = "Search attributes...",
        [Keys.FM_AL_Name] = "Name",
        [Keys.FM_AL_Group] = "Group",
        [Keys.FM_AL_Active] = "Active",
        [Keys.FM_AL_UsedIn] = "Used in",
        [Keys.FM_AL_Delete] = "Delete",
        [Keys.FM_AL_Close] = "Close",
        [Keys.FM_AL_ConfirmDelete] = "Delete attribute \"{0}\"? It is used in {1} categories.",
        [Keys.FM_AL_ConfirmDeleteEmpty] = "Delete attribute \"{0}\"?",
        [Keys.FM_AL_Add] = "Add",
        [Keys.FM_AL_Rename] = "Rename",
        [Keys.FM_AL_SetGroup] = "Group",
        [Keys.FM_AL_EnterName] = "Attribute name:",
        [Keys.FM_AL_EnterGroup] = "Group name:",

        [Keys.Btn_Yes] = "Yes",
        [Keys.Btn_No] = "No",
        [Keys.FM_CTE_ContextMenu_Rename] = "Rename",
        [Keys.FM_CTE_ContextMenu_AddChild] = "Add Subcategory",
        [Keys.FM_CTE_ContextMenu_Delete] = "Delete",
        [Keys.FM_CTE_NewCategory] = "New Category",
        [Keys.FM_CTE_Attributes] = "Attributes",
        [Keys.FM_AL_DeactivateTitle] = "Deactivate Attribute",
        [Keys.FM_AL_DeactivateMessage] = "Attribute is used in {0} categories. Deactivating will remove all bindings. Continue?",
        [Keys.FM_Confirm_Title] = "Confirm",
    };

    public static string? GetString(string key, Language language)
    {
        var dict = language == Language.EN ? En : Ru;
        return dict.TryGetValue(key, out var value) ? value : null;
    }

    public static bool ContainsKey(string key) => Ru.ContainsKey(key);

    public static IReadOnlyCollection<string> GetAllKeys() => Ru.Keys;

    public static string Format(string key, Language language, params object[] args)
    {
        var format = GetString(key, language);
        if (format is null) return $"[{key}]";
        try { return string.Format(format, args); }
        catch { return format; }
    }

    public static class Keys
    {
        public const string Btn_Cancel = nameof(Btn_Cancel);
        public const string Btn_Connect = nameof(Btn_Connect);
        public const string Btn_Insert = nameof(Btn_Insert);
        public const string Btn_Change = nameof(Btn_Change);
        public const string Btn_Save = nameof(Btn_Save);
        public const string Btn_Saved = nameof(Btn_Saved);
        public const string Btn_Delete = nameof(Btn_Delete);
        public const string Btn_Add = nameof(Btn_Add);
        public const string Btn_Import = nameof(Btn_Import);
        public const string Btn_Export = nameof(Btn_Export);
        public const string Tip_Import = nameof(Tip_Import);
        public const string Tip_Export = nameof(Tip_Export);
        public const string Btn_Confirm = nameof(Btn_Confirm);
        public const string Btn_Close = nameof(Btn_Close);
        public const string Btn_OK = nameof(Btn_OK);

        public const string Title_EditorSetup = nameof(Title_EditorSetup);
        public const string Heading_EditorSetup = nameof(Heading_EditorSetup);
        public const string Title_Settings = nameof(Title_Settings);
        public const string Title_FamilySelector = nameof(Title_FamilySelector);
        public const string Title_ConnType = nameof(Title_ConnType);
        public const string Title_CtcSetup = nameof(Title_CtcSetup);
        public const string Title_About = nameof(Title_About);

        public const string Tip_RotateCCW = nameof(Tip_RotateCCW);
        public const string Tip_RotationAngle = nameof(Tip_RotationAngle);
        public const string Tip_RotateCW = nameof(Tip_RotateCW);
        public const string Tip_AvailableSizes = nameof(Tip_AvailableSizes);
        public const string Tip_ChangeSize = nameof(Tip_ChangeSize);
        public const string Tip_FittingCtc = nameof(Tip_FittingCtc);
        public const string Tip_SelectFitting = nameof(Tip_SelectFitting);
        public const string Tip_InsertFitting = nameof(Tip_InsertFitting);
        public const string Tip_ReducerCtc = nameof(Tip_ReducerCtc);
        public const string Tip_SelectReducer = nameof(Tip_SelectReducer);
        public const string Tip_InsertReducer = nameof(Tip_InsertReducer);
        public const string Tip_ChainDecrement = nameof(Tip_ChainDecrement);
        public const string Tip_ChainIncrement = nameof(Tip_ChainIncrement);
        public const string Tip_ConnectAll = nameof(Tip_ConnectAll);
        public const string Tip_SelectFittingFamilies = nameof(Tip_SelectFittingFamilies);
        public const string Tip_SelectReducerFamilies = nameof(Tip_SelectReducerFamilies);
        public const string Tip_ChangeConnection = nameof(Tip_ChangeConnection);
        public const string Tip_Connect = nameof(Tip_Connect);

        public const string Label_Size = nameof(Label_Size);
        public const string Label_Network = nameof(Label_Network);
        public const string Label_Updates = nameof(Label_Updates);
        public const string Label_AvailableFamilies = nameof(Label_AvailableFamilies);
        public const string Label_FamilyFilter = nameof(Label_FamilyFilter);
        public const string Label_SelectedFamilies = nameof(Label_SelectedFamilies);
        public const string Label_Family = nameof(Label_Family);
        public const string Label_Symbol = nameof(Label_Symbol);
        public const string Label_Connector = nameof(Label_Connector);

        public const string Btn_ChangeConnection = nameof(Btn_ChangeConnection);
        public const string Btn_ConnectAll = nameof(Btn_ConnectAll);
        public const string Btn_AddFamily = nameof(Btn_AddFamily);
        public const string Btn_RemoveFamily = nameof(Btn_RemoveFamily);
        public const string Btn_Up = nameof(Btn_Up);
        public const string Btn_Down = nameof(Btn_Down);
        public const string Btn_CheckUpdates = nameof(Btn_CheckUpdates);
        public const string Btn_DownloadInstall = nameof(Btn_DownloadInstall);
        public const string Chk_CheckOnStartup = nameof(Chk_CheckOnStartup);

        public const string Tab_ConnectorTypes = nameof(Tab_ConnectorTypes);
        public const string Tab_MappingRules = nameof(Tab_MappingRules);

        public const string Col_Code = nameof(Col_Code);
        public const string Col_Name = nameof(Col_Name);
        public const string Col_Description = nameof(Col_Description);
        public const string Col_ConnType1 = nameof(Col_ConnType1);
        public const string Col_ConnType2 = nameof(Col_ConnType2);
        public const string Col_Direct = nameof(Col_Direct);
        public const string Col_Fittings = nameof(Col_Fittings);
        public const string Col_Transitions = nameof(Col_Transitions);

        public const string Status_Active = nameof(Status_Active);
        public const string Status_Processing = nameof(Status_Processing);
        public const string Status_SessionEnded = nameof(Status_SessionEnded);
        public const string Msg_AssignCtc = nameof(Msg_AssignCtc);

        public const string About_Author = nameof(About_Author);
        public const string About_Plugin = nameof(About_Plugin);
        public const string About_PluginDesc = nameof(About_PluginDesc);
        public const string About_Repo = nameof(About_Repo);
        public const string About_Language = nameof(About_Language);

        public const string Mapping_NewType = nameof(Mapping_NewType);
        public const string Mapping_NotSelected = nameof(Mapping_NotSelected);
        public const string Fitting_DirectConnect = nameof(Fitting_DirectConnect);
        public const string Fitting_TypeArrow = nameof(Fitting_TypeArrow);

        public const string PM_Title_Settings = "PM_Title_Settings";
        public const string PM_Title_Progress = "PM_Title_Progress";
        public const string PM_Tab_General = "PM_Tab_General";
        public const string PM_Tab_Purge = "PM_Tab_Purge";
        public const string PM_Tab_Views = "PM_Tab_Views";
        public const string PM_Tab_Naming = "PM_Tab_Naming";
        public const string PM_CurrentFile = "PM_CurrentFile";
        public const string PM_FilePath = "PM_FilePath";
        public const string PM_Folder = "PM_Folder";
        public const string PM_FileName = "PM_FileName";
        public const string PM_SharedFolder = "PM_SharedFolder";
        public const string PM_Browse = "PM_Browse";
        public const string PM_SyncBefore = "PM_SyncBefore";
        public const string PM_PurgeTitle = "PM_PurgeTitle";
        public const string PM_PurgeRvtLinks = "PM_PurgeRvtLinks";
        public const string PM_PurgeCadImports = "PM_PurgeCadImports";
        public const string PM_PurgeImages = "PM_PurgeImages";
        public const string PM_PurgePointClouds = "PM_PurgePointClouds";
        public const string PM_PurgeGroups = "PM_PurgeGroups";
        public const string PM_PurgeAssemblies = "PM_PurgeAssemblies";
        public const string PM_PurgeSpaces = "PM_PurgeSpaces";
        public const string PM_PurgeRebar = "PM_PurgeRebar";
        public const string PM_PurgeFabric = "PM_PurgeFabric";
        public const string PM_PurgeSheets = "PM_PurgeSheets";
        public const string PM_PurgeSchedules = "PM_PurgeSchedules";
        public const string PM_PurgeUnused = "PM_PurgeUnused";
        public const string PM_SelectAll = "PM_SelectAll";
        public const string PM_DeselectAll = "PM_DeselectAll";
        public const string PM_ViewsTitle = "PM_ViewsTitle";
        public const string PM_RefreshViews = "PM_RefreshViews";
        public const string PM_SearchViews = "PM_SearchViews";
        public const string PM_SelectedCount = "PM_SelectedCount";
        public const string PM_NamingTemplate = "PM_NamingTemplate";
        public const string PM_Blocks = "PM_Blocks";
        public const string PM_ExportMappings = "PM_ExportMappings";
        public const string PM_Preview = "PM_Preview";
        public const string PM_Col_Index = "PM_Col_Index";
        public const string PM_Col_Field = "PM_Col_Field";
        public const string PM_Col_ParseRule = "PM_Col_ParseRule";
        public const string PM_Col_Value = "PM_Col_Value";
        public const string PM_Col_Status = "PM_Col_Status";
        public const string PM_Col_ValidationCheck = "PM_Col_ValidationCheck";
        public const string PM_Col_SourceValue = "PM_Col_SourceValue";
        public const string PM_Col_TargetValue = "PM_Col_TargetValue";
        public const string PM_Col_FieldName = "PM_Col_FieldName";
        public const string PM_Col_DisplayName = "PM_Col_DisplayName";
        public const string PM_Col_Description = "PM_Col_Description";
        public const string PM_Col_Validation = "PM_Col_Validation";
        public const string PM_Col_Min = "PM_Col_Min";
        public const string PM_Col_Max = "PM_Col_Max";
        public const string PM_CurrentName = "PM_CurrentName";
        public const string PM_SharedName = "PM_SharedName";
        public const string PM_AddBlock = "PM_AddBlock";
        public const string PM_RemoveBlock = "PM_RemoveBlock";
        public const string PM_MoveUp = "PM_MoveUp";
        public const string PM_MoveDown = "PM_MoveDown";
        public const string PM_AddMapping = "PM_AddMapping";
        public const string PM_RemoveMapping = "PM_RemoveMapping";
        public const string PM_FieldLibrary = "PM_FieldLibrary";
        public const string PM_Title_FieldLibrary = "PM_Title_FieldLibrary";
        public const string PM_Title_AllowedValues = "PM_Title_AllowedValues";
        public const string PM_Title_ParseRule = "PM_Title_ParseRule";
        public const string PM_AllowedValuesButton = "PM_AllowedValuesButton";
        public const string PM_DuplicateField = "PM_DuplicateField";
        public const string PM_ValidField = "PM_ValidField";
        public const string PM_InvalidField = "PM_InvalidField";
        public const string PM_AddField = "PM_AddField";
        public const string PM_RemoveField = "PM_RemoveField";
        public const string PM_ValidationMode = "PM_ValidationMode";
        public const string PM_MinLength = "PM_MinLength";
        public const string PM_MaxLength = "PM_MaxLength";
        public const string PM_AddValue = "PM_AddValue";
        public const string PM_RemoveValue = "PM_RemoveValue";
        public const string PM_ParseMode = "PM_ParseMode";
        public const string PM_Delimiter = "PM_Delimiter";
        public const string PM_SegmentIndex = "PM_SegmentIndex";
        public const string PM_SegmentCount = "PM_SegmentCount";
        public const string PM_CharCount = "PM_CharCount";
        public const string PM_OpenMarker = "PM_OpenMarker";
        public const string PM_CloseMarker = "PM_CloseMarker";
        public const string PM_Marker = "PM_Marker";
        public const string PM_CharOffset = "PM_CharOffset";
        public const string PM_MarkerIndex = "PM_MarkerIndex";
        public const string PM_Result = "PM_Result";
        public const string PM_Remaining = "PM_Remaining";
        public const string PM_ExportName_CurrentLabel = "PM_ExportName_CurrentLabel";
        public const string PM_ExportName_FillFields = "PM_ExportName_FillFields";
        public const string PM_ExportName_Preview = "PM_ExportName_Preview";
        public const string PM_Step_Validate = "PM_Step_Validate";
        public const string PM_Step_Sync = "PM_Step_Sync";
        public const string PM_Step_TempProject = "PM_Step_TempProject";
        public const string PM_Step_Detach = "PM_Step_Detach";
        public const string PM_Step_Purge = "PM_Step_Purge";
        public const string PM_Step_Save = "PM_Step_Save";
        public const string PM_Step_Finish = "PM_Step_Finish";
        public const string PM_Result_NoSettings = "PM_Result_NoSettings";

        public const string FM_SearchPlaceholder = "FM_SearchPlaceholder";
        public const string FM_Import = "FM_Import";
        public const string FM_ImportFile = "FM_ImportFile";
        public const string FM_ImportFolder = "FM_ImportFolder";
        public const string FM_LoadToProject = "FM_LoadToProject";
        public const string FM_LoadAndPlace = "FM_LoadAndPlace";
        public const string FM_ExtractTypes = "FM_ExtractTypes";
        public const string FM_ImportData = "FM_ImportData";
        public const string FM_PlaceType = "FM_PlaceType";
        public const string FM_EditMetadata = "FM_EditMetadata";
        public const string FM_NoActiveDocument = "FM_NoActiveDocument";
        public const string FM_ImportProgress = "FM_ImportProgress";
        public const string FM_ColName = "FM_ColName";
        public const string FM_ColStatus = "FM_ColStatus";
        public const string FM_ColVersion = "FM_ColVersion";
        public const string FM_ColUpdated = "FM_ColUpdated";
        public const string FM_Save = "FM_Save";
        public const string FM_Cancel = "FM_Cancel";
        public const string FM_Name = "FM_Name";
        public const string FM_Description = "FM_Description";
        public const string FM_Category = "FM_Category";
        public const string FM_Tags = "FM_Tags";
        public const string FM_Status = "FM_Status";
        public const string FM_ImportSuccess = "FM_ImportSuccess";
        public const string FM_ImportError = "FM_ImportError";
        public const string FM_ImportPrepareError = "FM_ImportPrepareError";
        public const string FM_FamilyFileNotFound = "FM_FamilyFileNotFound";
        public const string FM_ImportResultFormat = "FM_ImportResultFormat";
        public const string FM_ImportDataError = "FM_ImportDataError";
        public const string FM_ImportFileToCategory = "FM_ImportFileToCategory";
        public const string FM_ImportFolderToCategory = "FM_ImportFolderToCategory";
        public const string FM_ImportDataForCategory = "FM_ImportDataForCategory";
        public const string FM_ImportDataProgress = "FM_ImportDataProgress";
        public const string FM_NoFamiliesInCategory = "FM_NoFamiliesInCategory";
        public const string FM_LoadSuccess = "FM_LoadSuccess";
        public const string FM_LoadAndPlaceSuccess = "FM_LoadAndPlaceSuccess";
        public const string FM_LoadError = "FM_LoadError";
        public const string FM_DuplicateSkipped = "FM_DuplicateSkipped";
        public const string FM_Title_MetadataEdit = "FM_Title_MetadataEdit";
        public const string FM_DbSwitched = "FM_DbSwitched";
        public const string FM_DbSwitchError = "FM_DbSwitchError";
        public const string FM_DbCreated = "FM_DbCreated";
        public const string FM_DbCreateError = "FM_DbCreateError";
        public const string FM_DbDeleted = "FM_DbDeleted";
        public const string FM_DbDeleteError = "FM_DbDeleteError";
        public const string FM_DbDeleteSingle = "FM_DbDeleteSingle";
        public const string FM_DbDeleteTitle = "FM_DbDeleteTitle";
        public const string FM_DbDeletePrompt = "FM_DbDeletePrompt";
        public const string FM_DbNewTitle = "FM_DbNewTitle";
        public const string FM_DbNewPrompt = "FM_DbNewPrompt";
        public const string FM_DbNewDefault = "FM_DbNewDefault";
        public const string FM_FamilyDeleted = "FM_FamilyDeleted";
        public const string FM_FamilyDeleteError = "FM_FamilyDeleteError";
        public const string FM_FamilyDeleteTitle = "FM_FamilyDeleteTitle";
        public const string FM_FamilyDeletePrompt = "FM_FamilyDeletePrompt";
        public const string FM_DeleteFromCatalog = "FM_DeleteFromCatalog";
        public const string FM_NoVersionSelected = "FM_NoVersionSelected";
        public const string FM_NoCategory = "FM_NoCategory";
        public const string FM_DbSelectPath = "FM_DbSelectPath";
        public const string FM_Disconnect = "FM_Disconnect";

        public const string FM_Update = "FM_Update";
        public const string FM_UpdateSuccess = "FM_UpdateSuccess";
        public const string FM_UpdateIdentical = "FM_UpdateIdentical";
        public const string FM_UpdateError = "FM_UpdateError";

        public const string FM_CTE_Title = "FM_CTE_Title";
        public const string FM_CTE_AddRoot = "FM_CTE_AddRoot";
        public const string FM_CTE_AddChild = "FM_CTE_AddChild";
        public const string FM_CTE_Rename = "FM_CTE_Rename";
        public const string FM_CTE_Delete = "FM_CTE_Delete";
        public const string FM_CTE_Import = "FM_CTE_Import";
        public const string FM_CTE_Export = "FM_CTE_Export";
        public const string FM_CTE_Close = "FM_CTE_Close";
        public const string FM_CTE_AddCategory = "FM_CTE_AddCategory";
        public const string FM_CTE_CategoryName = "FM_CTE_CategoryName";
        public const string FM_CTE_AddSubcategory = "FM_CTE_AddSubcategory";
        public const string FM_CTE_SubcategoryName = "FM_CTE_SubcategoryName";
        public const string FM_CTE_NewName = "FM_CTE_NewName";
        public const string FM_CTE_DeleteCategory = "FM_CTE_DeleteCategory";
        public const string FM_CTE_DeleteConfirm = "FM_CTE_DeleteConfirm";
        public const string FM_CTE_DeleteEmpty = "FM_CTE_DeleteEmpty";
        public const string FM_CTE_Deleted = "FM_CTE_Deleted";
        public const string FM_CTE_Saved = "FM_CTE_Saved";
        public const string FM_CTE_ImportTree = "FM_CTE_ImportTree";
        public const string FM_CTE_Imported = "FM_CTE_Imported";
        public const string FM_CTE_ExportTree = "FM_CTE_ExportTree";
        public const string FM_CTE_Exported = "FM_CTE_Exported";
        public const string FM_CTE_AttrExists = "FM_CTE_AttrExists";
        public const string FM_CTE_ExportAttrs = "FM_CTE_ExportAttrs";
        public const string FM_CTE_ExportFull = "FM_CTE_ExportFull";
        public const string FM_CTE_CategoriesAndAttrs = "FM_CTE_CategoriesAndAttrs";
        public const string FM_CTE_CategoryTree = "FM_CTE_CategoryTree";
        public const string FM_CTE_AttributesFor = "FM_CTE_AttributesFor";
        public const string FM_CTE_SelectCategory = "FM_CTE_SelectCategory";
        public const string FM_CTE_SelectCategoryHint = "FM_CTE_SelectCategoryHint";
        public const string FM_CTE_AllGroups = "FM_CTE_AllGroups";
        public const string FM_CTE_SearchAttrs = "FM_CTE_SearchAttrs";
        public const string FM_CTE_Inherited = "FM_CTE_Inherited";
        public const string FM_CTE_NewAttrName = "FM_CTE_NewAttrName";
        public const string FM_CTE_AddAttr = "FM_CTE_AddAttr";
        public const string FM_CTE_AttrLibrary = "FM_CTE_AttrLibrary";
        public const string FM_CTE_ImportJson = "FM_CTE_ImportJson";
        public const string FM_CTE_UnsavedChangesTitle = "FM_CTE_UnsavedChangesTitle";
        public const string FM_CTE_UnsavedChangesMessage = "FM_CTE_UnsavedChangesMessage";
        public const string FM_CTE_ExportColon = "FM_CTE_ExportColon";
        public const string FM_CP_Title = "FM_CP_Title";
        public const string FM_CP_Clear = "FM_CP_Clear";

        public const string FM_Tip_CreateDb = "FM_Tip_CreateDb";
        public const string FM_Tip_ConnectDb = "FM_Tip_ConnectDb";
        public const string FM_Tip_EditCategories = "FM_Tip_EditCategories";

        public const string FM_Properties = "FM_Properties";
        public const string FM_Props_SelectImage = "FM_Props_SelectImage";
        public const string FM_Props_AddFile = "FM_Props_AddFile";
        public const string FM_Tab_General = "FM_Tab_General";
        public const string FM_Tab_Content = "FM_Tab_Content";
        public const string FM_Tab_Attributes = "FM_Tab_Attributes";
        public const string FM_Tab_3DView = "FM_Tab_3DView";
        public const string FM_Props_Manufacturer = "FM_Props_Manufacturer";
        public const string FM_Props_Version = "FM_Props_Version";
        public const string FM_Props_Size = "FM_Props_Size";
        public const string FM_Props_Created = "FM_Props_Created";
        public const string FM_Props_Updated = "FM_Props_Updated";
        public const string FM_Props_NoAvatar = "FM_Props_NoAvatar";
        public const string FM_Props_ChangeImage = "FM_Props_ChangeImage";
        public const string FM_Props_RemoveImage = "FM_Props_RemoveImage";
        public const string FM_Props_Images = "FM_Props_Images";
        public const string FM_Props_Videos = "FM_Props_Videos";
        public const string FM_Props_Documents = "FM_Props_Documents";
        public const string FM_Props_LookupTables = "FM_Props_LookupTables";
        public const string FM_Props_Spreadsheets = "FM_Props_Spreadsheets";
        public const string FM_Props_Models3D = "FM_Props_Models3D";
        public const string FM_Props_Other = "FM_Props_Other";
        public const string FM_Props_Open = "FM_Props_Open";
        public const string FM_Props_Delete = "FM_Props_Delete";
        public const string FM_Props_SetPrimary = "FM_Props_SetPrimary";
        public const string FM_Props_Add = "FM_Props_Add";
        public const string FM_Props_NoAttributes = "FM_Props_NoAttributes";
        public const string FM_Props_NoAttributesDesc = "FM_Props_NoAttributesDesc";
        public const string FM_Props_PresetCategory = "FM_Props_PresetCategory";
        public const string FM_Props_NoPresets = "FM_Props_NoPresets";
        public const string FM_Props_3DComingSoon = "FM_Props_3DComingSoon";
        public const string FM_Props_3DDesc = "FM_Props_3DDesc";
        public const string FM_Props_FileInfo = "FM_Props_FileInfo";
        public const string FM_Props_Title = "FM_Props_Title";
        public const string FM_Props_NoAssets = "FM_Props_NoAssets";
        public const string FM_Props_ConfigurePreset = "FM_Props_ConfigurePreset";
        public const string FM_Props_ExtractAttributes = "FM_Props_ExtractAttributes";
        public const string FM_PE_Title = "FM_PE_Title";
        public const string FM_PE_ParameterName = "FM_PE_ParameterName";
        public const string FM_PE_DisplayName = "FM_PE_DisplayName";
        public const string FM_PE_AddParameter = "FM_PE_AddParameter";
        public const string FM_PE_RemoveParameter = "FM_PE_RemoveParameter";
        public const string FM_Props_XlsNote = "FM_Props_XlsNote";
        public const string FM_FamilyNotFoundAfterLoad = "FM_FamilyNotFoundAfterLoad";
        public const string FM_CannotDisconnectOnlyDatabase = "FM_CannotDisconnectOnlyDatabase";
        public const string FM_ErrorFormat = "FM_ErrorFormat";
        public const string FM_AL_Title = "FM_AL_Title";
        public const string FM_AL_Search = "FM_AL_Search";
        public const string FM_AL_Name = "FM_AL_Name";
        public const string FM_AL_Group = "FM_AL_Group";
        public const string FM_AL_Active = "FM_AL_Active";
        public const string FM_AL_UsedIn = "FM_AL_UsedIn";
        public const string FM_AL_Delete = "FM_AL_Delete";
        public const string FM_AL_Close = "FM_AL_Close";
        public const string FM_AL_ConfirmDelete = "FM_AL_ConfirmDelete";
        public const string FM_AL_ConfirmDeleteEmpty = "FM_AL_ConfirmDeleteEmpty";
        public const string FM_AL_Add = "FM_AL_Add";
        public const string FM_AL_Rename = "FM_AL_Rename";
        public const string FM_AL_SetGroup = "FM_AL_SetGroup";
        public const string FM_AL_EnterName = "FM_AL_EnterName";
        public const string FM_AL_EnterGroup = "FM_AL_EnterGroup";
        public const string FM_Props_NoCategoryAttr = "FM_Props_NoCategoryAttr";
        public const string FM_Props_NoBindingsAttr = "FM_Props_NoBindingsAttr";
        public const string FM_Props_NotImported = "FM_Props_NotImported";
        public const string FM_Props_NotImportedDesc = "FM_Props_NotImportedDesc";
        public const string FM_Props_Completeness = "FM_Props_Completeness";
        public const string FM_Props_TypeSize = "FM_Props_TypeSize";
        public const string Btn_Yes = "Btn_Yes";
        public const string Btn_No = "Btn_No";
        public const string FM_CTE_ContextMenu_Rename = "FM_CTE_ContextMenu_Rename";
        public const string FM_CTE_ContextMenu_AddChild = "FM_CTE_ContextMenu_AddChild";
        public const string FM_CTE_ContextMenu_Delete = "FM_CTE_ContextMenu_Delete";
        public const string FM_CTE_NewCategory = "FM_CTE_NewCategory";
        public const string FM_CTE_Attributes = "FM_CTE_Attributes";
        public const string FM_AL_DeactivateTitle = "FM_AL_DeactivateTitle";
        public const string FM_AL_DeactivateMessage = "FM_AL_DeactivateMessage";
        public const string FM_Confirm_Title = "FM_Confirm_Title";
    }
}
